/* custom.js — hand-authored scripts that survive build.py rebuilds.
   Loaded after data.js.

   window.CFI_SCRIPTS[lessonId] = { nodes: [...] }
     Seeds the "My Script" tab for that lesson with a pre-written teaching script.
     Every line stays editable / removable / note-able in the app.
     Node shape: { t: text, l: level (-1 section, 0 header, 1+ indent), b: bold }
*/
(function () {
  const S  = t => ({ t, l: -1, b: true });          // orange section
  const H  = t => ({ t, l: 0,  b: true });          // blue header
  const A  = t => ({ t, l: 1,  b: true, k: true }); // acronym letter / topic (k = force topic style)
  const P  = (t, l) => ({ t, l: l || 2, b: false }); // talking point
  const B  = (t, l) => ({ t, l: l || 2, b: true });  // emphasised point

  window.CFI_SCRIPTS = window.CFI_SCRIPTS || {};

  /* ============================================================
     I.A — Effects of Behavior & Communication on the Learning Process
     Flow follows the FIA Task A video; spine is the acronyms;
     detail augmented from the Backseat teach script + extra detail.
     ============================================================ */
  window.CFI_SCRIPTS['i-a-behavior-com-on-learning'] = { nodes: [

    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — "You have spent years assuming people understood you. Unless you know this material, they did not."'),
    P('Alternate: ask them to think of the best and worst instructor they ever had, and what actually made the difference.'),
    H('Overview'),
    P('Foundations of human behavior → motivation → human needs (PSBECS) → defense mechanisms (DR DR F CPR) → learner struggles → communication (SSR / COIL / LIQIR).'),
    H('What'),
    P('How human behavior — needs, personalities, motivation, emotions, age — and communication affect the learning process.'),
    H('Why'),
    P('Learning is a change in behavior as a result of experience. To cause that change I have to know why people act the way they do.'),
    B('Self-application: once you can name your own defense mechanisms and motivators, you use this every day — that is what makes the FOI worth learning instead of dreading.'),

    S('How:'),

    /* ---------------- foundations ---------------- */
    H('Foundations of Human Behavior — FI.I.A.K1a'),
    A('Two definitions of human behavior'),
    P('1. The factors that cause people to act in predictable ways — behavior is a product of experience.'),
    P('Ex: how two learners take praise after a good landing — one relaxes into it, the other gets complacent — depends on how praise landed for them long before they met me.', 3),
    P('2. The attempt to satisfy human needs — simple (food, water) through complex (respect, acceptance).'),
    A('Life course of humans'),
    P('As people mature they move from dependency toward self-direction, so the age of the learner shapes how I design the curriculum.'),
    B('Big picture: a working knowledge of behavior helps me understand the learner — that is the whole point of this task.'),

    H('Instructor & Learner Relationship — FI.I.A.K1b'),
    P('Everyone has an individual style of learning; working with that style benefits both of us.'),
    P('The match — or mismatch — between my teaching style and their learning style drives instructional satisfaction.'),
    B('My job is two-part: identify MY teaching style, identify THEIR learning style, and meet in the middle.'),
    P('I think out loud through every maneuver; a quiet, methodical learner needs the whiteboard and ten seconds of silence to process the exact same thing.', 3),
    P('RM — Recognizing & Accommodating Human Behavior (FI.I.A.R1): adjust for different personalities, motivators, and learning styles.'),

    /* ---------------- motivation ---------------- */
    H('Motivation — FI.I.A.K1c'),
    P('The driving force a person feels when trying to accomplish a goal; it lies at the heart of goals and is likely the dominant force governing progress.'),
    B('There is always an exchange — five a.m. drives and $200 an hour, traded for the right seat.'),
    A('Motivation can be positive or negative, tangible or intangible, subtle or obvious'),
    P('Positive — awards, recognition, tangible returns, group belonging, favorable self-image, a safe and pleasant environment.'),
    P('Positive is almost always the better choice.', 3),
    P('Negative — threats, fear, criticism. May work short term, but creates insecure training, inhibits learning, and damages the relationship.'),
    P('Avoid it with everyone except the most overconfident and impulsive learner.', 3),
    A('Maintaining motivation'),
    P('Praise incremental successes and tie each accomplishment back to the lesson objective; keep presenting new challenges.'),
    P('Drops are natural once the initial excitement wears off — remind them of their goals and normalize plateaus.'),
    B('Takeaway: identify how this learner is motivated, then use it to keep them moving.'),

    /* ---------------- maslow ---------------- */
    H('Human Needs — Maslow\'s Hierarchy: PSBECS — FI.I.A.K1d'),
    P('Levels of importance. Until the lower needs are met, the higher ones cannot be — and the learner is not ready to learn.'),
    A('P — Physiological'),
    P('Biological needs: food, rest, water, protection from the elements.'),
    P('A learner who came straight off a ten-hour shift without eating spends the lesson thinking about food, not about pitch and power.', 3),
    P('Get ahead of it — food, water, and a bathroom stop before we walk out, instead of burning their money in the air.', 3),
    A('S — Safety & Security'),
    P('Protection against danger, threats, and deprivation — at home and in the airplane.'),
    P('An airplane they overheard getting squawked yesterday: they will spend the hour listening to the engine instead of flying it.', 3),
    A('B — Belonging'),
    P('The need to associate, and to give and receive friendship — loneliness and alienation are real at an unfamiliar flight school.'),
    P('Counter: the learner who only trains at odd hours and never meets anybody quietly decides they do not belong here — introduce them around and get them a study partner.', 3),
    A('E — Esteem'),
    P('Internal (self-esteem): confidence, independence, achievement, competence.'),
    P('External (reputation): status, recognition, appreciation, respect of associates.'),
    P('High esteem → confident, independent, motivated. Low esteem → insecure, quicker to quit on a problem.', 3),
    P('The learner who apologizes after every single landing is telling me their esteem needs work before their technique does.', 3),
    B('If esteem is not met they are not ready to learn — build them up and push them out of the comfort zone.', 3),
    A('C — Cognitive & Aesthetic (added years after the original theory)'),
    P('Cognitive: the need to know and understand — understanding lets them control the situation and make informed decisions.'),
    P('Say "lean the mixture" and it is gone by next lesson; show them a fouled plug and what detonation does to a piston and they never skip it again.', 3),
    P('Aesthetic: emotional needs — can they see the beauty in what they are learning? Do they enjoy the school, the airplane, the flying?'),
    B('The part I control: three hours in a hot cockpit beside someone who sighs at every mistake is unbearable — nobody learns in that seat. If an instructor dislikes a learner, it affects the ability to teach.', 3),
    A('S — Self-Actualization'),
    P('Realizing one\'s own potential; reachable only when every other need is satisfied.'),
    B('I cannot make anyone self-actualize — but I control everything underneath it, so I clear the path and create the opportunity.', 3),
    P('Law of Readiness ties it together: the learner must be physically and mentally ready. Verify readiness every lesson (IMSAFE + motivation techniques).'),

    /* ---------------- defense mechanisms ---------------- */
    H('Defense Mechanisms — DR DR F CPR — FI.I.A.K1e'),
    P('Subconscious, almost automatic, ego-protecting reactions to unpleasant situations — used to soften failure, relieve guilt, and protect self-worth.'),
    B('Why I care: spotting one tells me the learner is frustrated or uncomfortable, so I can defuse the cause instead of arguing with the reaction.'),
    A('D — Denial'),
    P('Refusal to accept reality because it is too threatening.'),
    P('I tell them they lost 300 feet in the steep turn and they answer, "no, I was within a hundred the whole way around."', 3),
    A('R — Repression'),
    P('Uncomfortable thoughts pushed into inaccessible areas of the unconscious mind.'),
    P('At debrief they cannot recall one thing about the go-around we just flew — the part that scared them is simply gone.', 3),
    A('D — Displacement'),
    P('Unconscious shift of emotion from the original object to a less threatening substitute.'),
    P('Frustrated in the pattern, and on the walk back in it is the airplane, the dispatcher, and the schedule that are the problem.', 3),
    B('I have full authority to say: "you seem frustrated — I am not comfortable flying right now." Use it.', 3),
    A('R — Rationalization'),
    P('Subconscious justification of actions that would otherwise be unacceptable; they sincerely believe the excuse.'),
    P('"These radios are junk" — after missing two calls because they were behind the airplane.', 3),
    A('F — Fantasy'),
    P('Daydreaming about how things should be rather than doing something about how they are.'),
    P('Dangerous: they can become satisfied with the daydream and stop chasing the goal — the whole debrief is about which airline they will fly for, not the three landings we need to fix.', 3),
    A('C — Compensation'),
    P('Disguising a weak quality by emphasizing a more positive one; may substitute an easier goal for the preferred one.'),
    P('"My landings are rough, but nobody in the class works the radio like I do."', 3),
    A('P — Projection'),
    P('Blame relegated to others for their own shortcomings and mistakes.'),
    P('"You never showed me that" — about the checklist flow we ran together the last two lessons.', 3),
    A('R — Reaction Formation'),
    P('Protecting against a dangerous desire by developing the opposite attitude — accepting or reacting opposite of the truth to avoid discomfort.'),
    P('White knuckles and a shaky voice after the unusual attitude recovery, and when I ask, they laugh and say that was fun. Consider ending the lesson right there — nothing more is going in.', 3),
    P('Non-aviation: insisting you were never that interested in the job you just got rejected from.', 3),
    A('Dealing with defense mechanisms'),
    B('Never confront the mechanism directly — that makes them more defensive. Create an environment where they do not need to defend themselves and address the root cause.'),

    /* ---------------- learner struggles ---------------- */
    S('Learner Struggles — Emotional Reactions (FI.I.A.K2)'),
    P('Analyze the learner\'s behavior before, during, and after every lesson so problems get identified and solved.'),
    H('Anxiety — FI.I.A.K2a'),
    P('"A state of mental uneasiness arising from fear" — the most significant psychological factor affecting flight instruction.'),
    P('Why: flying is threatening to the unfamiliar, and fear of falling is nearly universal.'),
    P('Reactions: hesitancy to act, the impulse to do something even if wrong, or freezing.'),
    P('Watch for it at: first flight, first solo, solo cross-countries, checkrides.'),
    P('Counter: normalize the feeling, reinforce enjoyment of flying, teach them to cope, and rebuild confidence — I would not sign them off unready.'),
    B('Never say "do not mess up my pass rate."'),
    H('Stress — FI.I.A.K2a'),
    P('The body\'s response to high demand.'),
    B('Low stress improves performance; high stress significantly degrades it. Finding that line per learner is the craft.'),
    P('Normal reactions: fast, accurate responses within the limits of their experience and training.'),
    P('First few landing lessons — I work the radio so their whole brain can go to the picture out the window.', 3),
    P('Two weeks from the checkride at a busy Class D — they work the radio, spot the traffic, and land it while I stay quiet.', 3),
    A('Abnormal reactions to stress (this one is about MY safety)'),
    P('Random, illogical, absent, or inadequate responses; over-cooperation, extreme self-control, inappropriate laughter or singing, rapid emotional shifts.'),
    P('If it concerns me: get on the ground and defuse the situation.'),
    P('After: refrain from instructing them, arrange an evaluation flight with a second instructor, and report to the FAA if serious psychological issues are at play.'),
    B('DO NOT ENDORSE THEM — I am liable.'),
    H('Impatience — FI.I.A.K2b'),
    P('Seeks the ultimate objective without considering the means — the learner who wants to solo by hour twelve and treats slow flight as a speed bump.'),
    P('Counter: present training one step at a time with clearly stated goals, tailored to their pace. Visible progress is what keeps them.'),
    H('Worry or Lack of Interest — FI.I.A.K2c'),
    P('Those worried or emotionally upset are not ready to learn and get little from instruction.'),
    P('Counter: divert attention from the worry to the task at hand.'),
    P('Prevent: make sure they know exactly how they progressed and what is deficient — say nothing about their landings and a worrier decides they were terrible.'),
    P('For lack of interest: remind them of the goals they told me on day one.'),
    H('Physical Discomfort, Illness, Fatigue & Dehydration — FI.I.A.K2d'),
    P('All slow the rate of learning and should be mitigated — run PAVE / IMSAFE. Ties straight back to physiological, the base of PSBECS.'),
    P('Fatigue is one of the most treacherous hazards to flight safety; it impairs judgment and decision making.'),
    P('Acute: normal part of everyday living. Chronic: physiological/psychological problems — do not fly.', 3),
    P('Dehydration reduces alertness; heatstroke is the body failing to control temperature. Carry water, keep it cool, wear light clothing.'),
    H('Apathy Due to Inadequate Instruction — FI.I.A.K2e'),
    P('Provide well-planned, accurate, meaningful instruction taught to the level of the learner.'),
    B('Let the ego go. Be vulnerable and own what I do not know — "great question, I am not sure; let me find out and get back to you."'),
    P('Pretend to know everything, get fact-checked once, and they will not believe anything I say afterward.'),
    P('Once the instructor loses their confidence it is very hard to regain, and learning is diminished.'),
    P('Bonus: "I stumped the CFI" sparks a competitive fire that pushes us both.', 3),
    H('Teaching the Adult Learner — FI.I.A.K3'),
    P('Most student pilots are adults: autonomous and self-directed, goal and relevancy oriented, practical, drawing on a foundation of life experience, and needing to be shown respect.'),
    P('They may be slower to grasp a brand-new concept than a younger learner — the same reason a new language comes easier at ten than at forty.'),
    P('So I: clarify expectations early, use an organized syllabus with clear objectives, let them control pace, use scenario-based training, connect new ideas to what they know, and refrain from spoon-feeding.'),

    /* ---------------- communication ---------------- */
    S('Effective Communication — FI.I.A.K4'),
    P('It does not happen automatically — I have to develop a style that actually conveys information.'),
    P('Communication takes place when a person transmits ideas or feelings to another; its effectiveness is measured by how closely the idea received matches the idea sent.'),
    B('Goal: a change in behavior.'),
    H('Basic Elements — SSR — FI.I.A.K4a'),
    A('S — Source (the sender, speaker, transmitter — me)'),
    P('Effectiveness rests on three factors: ability to select and use language, revealing a positive attitude about self and material, and material that is accurate, current, and stimulating.'),
    A('S — Symbol (the words, signs, or oral/visual/tactile codes carrying the message)'),
    P('Choose the symbols best for opening, explaining, clarifying, emphasizing, and closing — and the medium best suited to carry them.'),
    P('Monitor feedback; if it is not landing, change the symbol — a traffic pattern described out loud is a blur, drawn on the whiteboard it is obvious.', 3),
    P('Learners need feedback on how they are doing; deliver negative feedback in private only.'),
    A('R — Receiver (the listener, reader, learner)'),
    P('Communication is effective when the receiver reacts with understanding and changes behavior accordingly.'),
    P('Not everyone learns the same way — using multiple approaches is most effective.'),
    H('Barriers to Effective Communication — COIL — FI.I.A.K4b / R2'),
    A('C — Confusion between the symbol and the symbolized object'),
    P('The meaning or intent of the words, or the context, is not clear — sarcasm, or a word with two meanings.'),
    P('"Level off" — do they stop the climb, or roll the wings level?', 3),
    A('O — Overuse of Abstractions'),
    P('Abstractions are general rather than specific words; they may not evoke the same experience in the learner\'s mind.'),
    P('"Slow it down" on final — pitch, power, or flaps? Say "1500 RPM and 65 knots" instead.', 3),
    A('I — Interference'),
    P('The message gets disrupted or truncated — confirm it was understood.'),
    P('External factors outside my control: physiological (injury, hearing loss), environmental (noise, radio static, busy frequency), psychological (fear, mistrust).'),
    P('Prior learning interferes too — years of driving says steer with your hands, so the yoke fights them all the way down the taxiway.', 3),
    A('L — Lack of Common Experience'),
    B('The greatest single barrier to effective communication.'),
    P('I must speak the same language as the learner; when specific terminology is required, confirm they understand it.'),
    P('"Make short approach," "squawk VFR," "expedite" — obvious to me, noise to a ten-hour student unless I brief the words on the ground.', 3),
    P('Generational gap between a young CFI and an adult learner counts here too.', 3),
    H('Developing Communication Skills — LIQIR — FI.I.A.K4c'),
    A('L — Listening'),
    P('Listen actively and listen to understand rather than to refute — notes, eye contact, and hear the question they are actually asking.'),
    A('I — Instructional Communication'),
    P('Know the topic cold and be confident; use stories and past experience to illustrate points and hold attention; evaluate to confirm the level of understanding.'),
    A('Q — Questioning'),
    P('Good questioning determines how well the learner understands. Ask open-ended, focused questions; paraphrase and perception-check to confirm.'),
    A('I — Instructional Enhancement'),
    P('The deeper my knowledge of an area, the better I convey it — and the more confident and efficient I am.'),
    B('If I cannot explain it simply, I do not understand it well enough yet.', 3),
    A('R — Role Playing'),
    P('Practice instructing to build the skill; play ATC for the learner so the radios stop being a threat and their confidence builds before the real thing.'),

    S('Conclusion'),
    P('Brief review: foundations → motivation → PSBECS → DR DR F CPR → learner struggles → SSR / COIL / LIQIR.'),
    P('Tie back to why: every one of these is a tool for spotting what is blocking the learner and removing it.'),
  ]};

  /* ============================================================
     I.B — Learning Process
     Acronym spine: A MAP · RIC · G-STEP · MUA · REEPIR · CAP
     (RUAC/ARVOI/OIPH) · CTE · CAAR · DBR · SM · CULT DR ·
     FIRRS · MALAMP
     ============================================================ */
  window.CFI_SCRIPTS['i-b-learning-process'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — "This lesson explains why you will — or will not — remember this lesson."'),
    H('Overview'),
    P('Definition (A MAP) → learning theory (RIC) → perception (G-STEP) → knowledge (MUA) → laws (REEPIR) → domains (CAP) → skill (CAAR, DBR) → errors (SM, CULT DR) → memory & forgetting (FIRRS) → retention (MALAMP) → transfer.'),
    H('What'),
    P('Understanding how people learn and applying that knowledge to the learning environment.'),
    H('Why'),
    P('Effective teaching starts with knowing how learning actually works — the subject, the learner, and the process.'),

    S('How:'),

    H('Definition of Learning — A MAP — FI.I.B.K1'),
    A('A — A change in behavior as a result of experience'),
    P('The core definition: relatively permanent change in behavior or cognition resulting from experience.'),
    A('M — Multifaceted'),
    P('Involves verbal, conceptual, perceptual, motor, problem-solving, and emotional elements all at once.'),
    A('A — Active process'),
    P('The learner has to DO something with the material — you cannot pour knowledge into a passive student.'),
    A('P — Purposeful'),
    P('Each learner has their own goals; learning sticks when it connects to what THEY are trying to accomplish.'),
    B('Same four ideas = "Characteristics of Learning (RAMP)": Result of experience, Active, Multifaceted, Purposeful. One list, two acronyms — know both names.'),

    H('Learning Theory — Behaviorism & Cognitive (RIC) — FI.I.B.K2'),
    A('Behaviorism'),
    P('Behavior can be predicted and shaped by reward and punishment (Pavlov\'s dog).'),
    P('Popularity has waned — learning is more complex than stimulus and response.', 3),
    B('Keep its best principle: immediate, specific positive reinforcement when the learner does something right.', 3),
    A('Cognitive Theory — the three branches RIC'),
    P('Focuses on what happens inside the learner\'s mind: how the brain observes, learns, problem-solves, decides.'),
    P('R — Reflective Thought Theory: learning develops from reflection.', 3),
    B('Action: spark reflection by having the learner self-critique the flight during the debrief.', 3),
    P('I — Information Processing Theory: the brain processes, stores, retrieves, and applies information like a computer.', 3),
    P('C — Constructivism: learners build new understanding on top of old experience — teach high-to-low pressure before teaching lift.', 3),

    S('Perception to Understanding'),
    H('Perceptions & Insight — FI.I.B.K3'),
    A('Perceptions'),
    P('All initial learning comes from perceptions, received through the five senses — most through sight (~75%).'),
    B('Action: teach multi-sensory whenever possible; combining senses accelerates learning.'),
    A('Insight'),
    P('When perceptions come together into a meaningful whole — the "aha" moment.'),
    P('Stall example: engine quiets + airspeed decays + buffet in the seat = all those perceptions click into "we are about to stall."', 3),
    H('Factors That Affect Perception — G-STEP'),
    A('G — Goals & Values'),
    P('Every experience is filtered through the person\'s beliefs and values.'),
    P('A CFI who sees the job as hour-building teaches and perceives differently than one who is there to make a difference.', 3),
    A('S — Self-Concept'),
    P('Self-image drives openness: a confident learner stays open to new experiences; an insecure one may quit when it gets tough.'),
    A('T — Time & Opportunity'),
    P('Learning takes proper sequence AND enough time — airspace, taxi, landings, and patterns come before anyone talks about solo.'),
    A('E — Element of Threat'),
    P('Threat narrows perception to tunnel vision on whatever is threatening.'),
    P('Alternator light flashes red — breaker reset, all good — but the student keeps staring at that corner of the panel.', 3),
    A('P — Physical Organism'),
    P('The body is the perceptual apparatus; it has to work. A plugged nose cannot smell the electrical fire before it is visible.'),

    H('Acquiring Knowledge — MUA — FI.I.B.K4'),
    A('M — Memorize'),
    P('Learners memorize facts first, before real understanding exists.'),
    A('U — Understand'),
    P('The memorized pieces get organized into how things actually work.'),
    A('A — Application'),
    P('Using that understanding to solve real problems — the level you actually fly at.'),

    H('Laws of Learning — REEPIR — FI.I.B.K5'),
    A('R — Readiness'),
    P('Basic needs met = mentally, physically, emotionally ready. Ties straight to Maslow and IMSAFE.'),
    A('E — Effect'),
    P('Pleasant or satisfying feelings strengthen learning; frustration and fear weaken it.'),
    A('E — Exercise'),
    P('Practice makes permanent — use it or lose it.'),
    A('P — Primacy'),
    B('What is learned FIRST creates a near-unshakable impression — so teach it right the first time; unteaching is far harder than teaching.'),
    A('I — Intensity'),
    P('An engaging, vivid lesson sticks; a dull one does not. The real airplane beats the whiteboard.'),
    A('R — Recency'),
    P('The most recently learned is best remembered — why we debrief immediately, and why checkride prep reviews everything.'),

    H('Domains of Learning — CAP — FI.I.B.K6'),
    A('C — Cognitive Domain (knowledge) — RUAC'),
    P('Rote → Understanding → Application → Correlation.'),
    P('Rote: recites V-speeds. Understanding: knows why. Application: uses them in the flare. Correlation: connects gusty winds to adding half the gust factor without being told.', 3),
    A('A — Affective Domain (attitudes/feelings) — ARVOI'),
    P('Awareness → Response → Value → Organize → Integrate.'),
    P('The safety-culture domain: from hearing about checklist discipline to being someone who would never skip one.', 3),
    A('P — Psychomotor Domain (physical skills) — OIPH'),
    P('Observe → Imitate → Practice → Habituate.'),
    P('Watch me land → follow me through → your landings with my coaching → landings are automatic.', 3),

    H('Scenario-Based Training — CTE — FI.I.B.K8'),
    P('Real-world scenarios that force the learner to problem-solve — SBT is how we build HOTS/ADM.'),
    A('C — Clear objective'),
    P('What do you want to teach and why?'),
    A('T — Tailored to the learner'),
    P('Match the scenario to their skill level.'),
    A('E — Environmental factors'),
    P('A fuel-emergency scenario on the ground gives thinking time; the same problem in the air does not. Choose the environment deliberately.'),

    S('Acquiring Skills'),
    H('Stages of Skill Acquisition — CAAR — FI.I.B.K9'),
    A('C — Cognitive stage'),
    P('Memorizing what to do — thinking through every step of the maneuver.'),
    A('A — Associative stage'),
    P('Can perform the skill and assess their own performance afterward, but it takes focus and effort.'),
    A('AR — Automatic Response stage'),
    P('Performs with little conscious effort, freeing attention for other tasks — radio calls during a landing.'),
    H('Building the Skill'),
    A('Knowledge of results'),
    B('Action: tell learners immediately when they are wrong — never let them practice mistakes.'),
    A('Power Law of Practice'),
    P('Speed and accuracy improve as a power of the number of repetitions — improvement is fast early, slower later.'),
    A('Learning plateaus'),
    P('Learning slows after rapid progress — normal, everyone hits them.'),
    B('Action: normalize the plateau and keep them practicing through it.', 3),
    H('Types of Practice — DBR'),
    A('D — Deliberate (initial)'),
    P('Specific goal, detailed plan, specific feedback.'),
    A('B — Blocked (middle)'),
    P('Same skill over and over until it reaches the automatic response stage.'),
    A('R — Random (final)'),
    P('Mix the skills up — best for retention. This is checkride-prep mode.'),
    H('Evaluation vs. Critique'),
    P('Evaluation: broad assessment of performance — also checks YOUR teaching effectiveness.'),
    P('Critique: monitoring practice and giving feedback so the skill develops correctly — constructive, never ridicule.'),

    S('Attention & Errors'),
    H('Distractions, Interruptions, Fixation & Inattention — FI.I.B.K10'),
    A('Distraction'),
    P('An unexpected event that CAN disrupt attention — passenger asks a question on short final; pilot lands first.'),
    A('Interruption'),
    P('The learner actually diverts attention to it — answers the question and forgets the position call. Distractions become interruptions.'),
    A('Fixation'),
    P('Locking onto one task above all else — instrument students fixating on a single gauge.'),
    A('Inattention'),
    P('Not noticing what is going on around them — fixation leads here: staring at the altimeter, neglecting everything else.'),
    H('Errors — SM — FI.I.B.K11'),
    A('S — Slip'),
    P('Intended one thing, did another — pulls the mixture instead of the throttle. Signals a lack of practice.'),
    A('M — Mistake'),
    P('Did exactly what they intended, and it was wrong — dumps full flaps abeam the numbers. Signals a gap in knowledge.'),
    B('Slip → more practice. Mistake → more teaching. Diagnose which one it was before you fix it.'),
    H('Reducing Errors — CULT DR'),
    P('C — Checking for errors: scan the instruments.'),
    P('U — Using tools: heading bug, altitude bug, timers, checklists, writing things down.'),
    P('L — Learning and practicing — correctly.'),
    P('T — Taking your time: slow is smooth, smooth is fast.'),
    P('D — Developing routines: a flow for takeoff, level-off, climb.'),
    P('R — Raising awareness: know which situations raise the risk.'),

    S('Memory & Forgetting'),
    H('The Three Memory Systems — FI.I.B.K12'),
    A('Sensory memory'),
    P('Takes in everything through the five senses; discards what it deems unimportant.'),
    A('Short-term memory'),
    P('Holds information about 30 seconds — then it fades or transfers to long-term, depending on the value the learner puts on it.'),
    A('Long-term memory'),
    P('Effectively unlimited and relatively permanent. What transfers usually has emotional ties.'),
    B('Action: solidify important material by invoking positive emotion — stories, humor, memorable moments.', 3),
    P('Usage matters: information used frequently and recently is the easiest to retrieve.'),
    H('Forgetting — FIRRS — FI.I.B.K12b'),
    A('F — Fading'),
    P('Use it or lose it.'),
    A('I — Interference'),
    P('New, similar information overwrites the old — V-speeds across different airplanes.'),
    A('R — Retrieval failure'),
    P('Lost between short-term and long-term — never solidified.'),
    A('R — Repression'),
    P('Unconscious effort to forget — turbulence terror as a kid becomes an unexplained fear of turbulence as a student.'),
    A('S — Suppression'),
    P('CONSCIOUS effort to forget something upsetting or embarrassing.'),
    H('Retention of Learning — MALAMP — FI.I.B.K13'),
    P('"I can\'t learn without MALAMP":'),
    P('M — Meaningful repetition: 3–4 reps give maximum retention effect.'),
    P('A — Association: hook new knowledge to something known — descend, pull carb heat.'),
    P('L — Learning with all senses: the feeling in your seat during a steep turn teaches too.'),
    P('A — Attitude: learners must WANT to learn for it to stick.'),
    P('M — Mnemonics: acronyms, rhymes, phrases — this entire lesson is proof.'),
    P('P — Praise: responses that produce positive feelings get repeated.'),
    H('Transfer of Learning — FI.I.B.K14'),
    A('Positive transfer'),
    P('A past skill helps the new one — knows car engines, picks up aircraft engines fast.'),
    A('Negative transfer'),
    P('A past skill fights the new one — turning the yoke on the ground like a steering wheel.'),
    B('Action: anticipate negative transfer from driving, gaming, and other aircraft — and brief it before it bites.'),

    S('Conclusion'),
    P('Review: A MAP → RIC → G-STEP → MUA → REEPIR → CAP (RUAC/ARVOI/OIPH) → CTE → CAAR → DBR → SM → CULT DR → FIRRS → MALAMP → transfer.'),
    P('Every acronym here is a lever: readiness before the lesson, primacy during it, meaningful repetition after it.'),
  ]};

  /* ============================================================
     I.C — Course Development, Lesson Plans & Classroom Training
     Acronym spine: PPAR · SPAM · DCC · IDC (AMO) · FIT · ORDRR
     ============================================================ */
  window.CFI_SCRIPTS['i-c-course-development'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — teaching is the actual job of a flight instructor; the flying is the classroom.'),
    H('Overview'),
    P('Teaching process (PPAR) → essential skills (SPAM) → course/syllabus/lesson plans → objectives (DCC) → lesson organization (IDC/AMO) → delivery methods (FIT, ORDRR) → e-learning & aids → PBL and integrated flight instruction.'),
    H('What'),
    P('How to organize material and deliver it so a learner can actually absorb it.'),
    H('Why'),
    P('You can be a great pilot and a poor teacher. Structure is what turns knowledge into instruction.'),

    S('How:'),

    H('The Teaching Process — PPAR — FI.I.C.K1a'),
    P('Organizing material and teaching it so the student can understand:'),
    A('P — Preparation / Planning'),
    P('Syllabus, lesson plans, objectives, materials.'),
    A('P — Presentation'),
    P('Deliver the material by the method that fits the content and the learner.'),
    A('A — Application'),
    P('The learner performs — the skill or knowledge gets used.'),
    A('R — Review / Assessment'),
    P('Measure it against standards and feed it back.'),

    H('Essential Teaching Skills — SPAM — FI.I.C.K1b'),
    A('S — Subject Matter Expertise'),
    P('Know the aviation content cold — there is a lot of it.'),
    A('P — People Skills'),
    P('Understand the learner, satisfy their needs, communicate well.'),
    A('A — Assessment Skills'),
    P('Judge skill and development accurately and guide it (all of Task D).'),
    A('M — Management Skills'),
    P('Plan, lead, and organize every part of the learner\'s training — including time inside each flight lesson.'),
    P('Backseat orders the same four as "MAPS" — same skills, either order.', 3),

    S('Course Design & Planning'),
    H('Levels of Planning — FI.I.C.K2'),
    A('Course of Training'),
    P('The destination: the complete series of studies leading to the certificate or rating.'),
    A('Syllabus'),
    P('The route: a step-by-step, building-block sequence of lessons with review and assessment built in.'),
    A('Lesson Plan'),
    P('Today\'s leg: an organized outline for a single instructional period.'),
    A('Blocks of Learning'),
    P('Discrete skills that can each be taught, measured, and mastered — start broad, build the foundation, stack blocks on top.'),
    P('Master blocks individually; the syllabus arranges them in a logical sequence.', 3),

    H('Lesson Objectives — FI.I.C.K3'),
    A('Two types: Performance-Based and Decision-Based'),
    P('Performance-based: define exactly what is done and how — the early-training workhorse.'),
    P('Decision-based: designed to develop ADM and judgment — shift toward these as training progresses.'),
    A('Performance-Based Objectives — DCC'),
    P('D — Description of the skill: what behavior is being learned (a maximum-performance climbing turn — chandelle).'),
    P('C — Conditions: the rules for the demonstration (no more than 30° bank).'),
    P('C — Criteria: measurable standards — no question whether they passed (±10° on rollout).'),
    A('Importance of the ACS'),
    P('The ACS supplies the specific performance standards for certification.'),
    B('Action: use the ACS standards, but deliver them through scenarios rather than isolated maneuvers.', 3),

    S('Organizing & Delivering Lessons'),
    H('Organization of Material — IDC — FI.I.C.K4'),
    A('I — Introduction — AMO'),
    P('A — Attention: story, video, joke — earn the next 30 minutes.'),
    P('M — Motivation: why this matters to THEM.'),
    P('O — Overview: tell them what will be covered.'),
    A('D — Development'),
    P('The main body, organized in a way that makes sense:'),
    P('Past to present · Simple to complex · Known to unknown · Most frequently used to least.', 3),
    A('C — Conclusion'),
    P('Return to the important elements and tie them to the objective — "now that we understand left-turning tendencies, we can expect them and counteract with right rudder on takeoff."'),

    H('Training Delivery Methods — FI.I.C.K5'),
    A('Lecture — FIT'),
    P('Best for large groups, new information, and time management.'),
    P('F — Formal: inform or persuade with little participation — lots of info, little time.', 3),
    P('I — Illustrated talk: visual aids — gyro, pictures, the model airplane.', 3),
    P('T — Teaching lecture: delivered to allow learner participation.', 3),
    A('Discussion'),
    P('Short lecture, then discussion — the learner talks their way to understanding.'),
    A('Guided Discussion — ORDRR question types'),
    P('The goal is to DRAW OUT what the learners know rather than tell them:'),
    P('O — Overhead: to the whole group, the big question.', 3),
    P('R — Rhetorical: ask, pause, answer it yourself.', 3),
    P('D — Direct: aimed at one specific person.', 3),
    P('R — Reverse: they ask me, I answer with a question back.', 3),
    P('R — Relay: they ask me, I pass it to another learner.', 3),
    A('Cooperative / Group Learning'),
    P('Small groups organized to maximize learning from each other.'),
    A('Demonstration–Performance'),
    P('Explanation → Demonstration → Learner performance with supervision → Evaluation. The backbone of flight training.'),
    A('Drill and Practice'),
    P('Repetition builds retention and skill — connects straight to the Law of Exercise.'),

    H('E-Learning & Instructional Aids — FI.I.C.K6/K7'),
    A('E-Learning'),
    P('Self-paced learning (Sporty\'s, King, sims, role-playing, even games).'),
    P('Pros: time-flexible, cost-effective, easily updated. Cons: limited feedback, cannot ask questions.', 3),
    P('Aviation Training Devices: BATD → AATD → FTD → full flight simulators.', 3),
    A('Effective instructional aids'),
    P('Cover the key points, straightforward and factual, relatively simple.'),
    P('Reasons: assist the instructor, clarify relationships, help learners connect concepts.', 3),
    B('Action: establish the objective first, gather the data, organize the lesson plan — THEN pick which ideas need an aid.', 3),
    P('Types: whiteboard, print, syllabi/records/maneuvers guides, projected material, video, models and mock-ups.'),

    S('Advanced Instructional Methods'),
    H('Problem-Based Instruction & HOTS — FI.I.C.K9'),
    P('Lessons built on real-life situations with no single right answer — this is how you develop higher-order thinking (HOTS).'),
    P('Set up the problem → determine learning outcomes → solve it → reflect on the process → consider other solutions through guided discovery → re-evaluate.'),
    P('Scenario-Based Training is the PBL form we use most in flight training.', 3),
    H('Integrated Flight Instruction — FI.I.C.K8'),
    P('Every maneuver taught by BOTH outside visual references and instrument indications, from the first time it is introduced.'),
    P('Improves control, coordination, landings, and overall competency.'),
    B('90% outside, 10% inside — never let instrument focus kill see-and-avoid.'),
    B('Build judgment with PBL; build habits with integrated flight instruction.'),

    S('Conclusion'),
    P('Review: PPAR → SPAM → course/syllabus/lesson plan → DCC objectives → IDC (AMO intro) → FIT / ORDRR delivery → aids → PBL + IFI.'),
    P('A lesson plan is not paperwork — it is the difference between teaching and just talking.'),
  ]};

  /* ============================================================
     I.D — Student Evaluation, Assessment & Testing
     Acronym spine: FAST COCO · V CROUD · RRRR · WAC · CAB CAP ·
     TOP BIT
     ============================================================ */
  window.CFI_SCRIPTS['i-d-student-evaluation'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — a grade the learner does not understand teaches nothing; assessment is teaching.'),
    H('Overview'),
    P('Purpose → effective assessment (FAST COCO) → traditional tests (V CROUD) → authentic assessment (RRRR, maneuver grades) → choosing assessments (WAC) → critique types & ground rules → questioning (CAB CAP / TOP BIT) → assessing piloting ability.'),
    H('What'),
    P('How to measure a learner\'s progress and feed it back so it improves performance.'),
    H('Why'),
    P('Assessment highlights where they are lacking and excelling — it steers every lesson that follows.'),

    S('How:'),

    H('Characteristics of an Effective Assessment — FAST COCO — FI.I.D.K1'),
    P('F — Flexible: fit the learner and the occasion.'),
    P('A — Acceptable: the learner must accept YOU — your qualifications and sincerity — before they accept the critique.'),
    P('S — Specific: no doubt what was good, what was poor, and how to improve.'),
    P('T — Thoughtful: never ridicule or anger — respect their need for self-esteem and approval.'),
    P('C — Comprehensive: strengths AND weaknesses.'),
    P('O — Objective: standards-based, not your opinions or preferences — the ACS is an objective yardstick.'),
    P('C — Constructive: the learner must benefit; it corrects the deficient areas.'),
    P('O — Organized: logical pattern, or it loses its impact.'),

    H('Traditional Assessment — V CROUD — FI.I.D.K2'),
    P('Written tests: multiple choice, matching, true/false. A good grade may not reflect ability. A good test has:'),
    P('V — Validity: measures the lesson objectives and nothing else.'),
    P('C — Comprehensiveness: samples a good cross-section of the knowledge.'),
    P('R — Reliability: yields consistent results.'),
    P('O — Objectivity: can be graded consistently.'),
    P('U — Usability: easy to give, read, and grade.'),
    P('D — Discrimination: separates those who know the material from those who do not.'),

    H('Authentic Assessment — FI.I.D.K3'),
    P('The learner performs REAL-WORLD tasks and demonstrates meaningful application — no multiple choice. The checkride is one.'),
    A('Learner-Centered Assessment — RRRR (4 open-ended steps)'),
    P('R — Replay: the student verbally replays the lesson — gives the steps of the maneuver.'),
    P('R — Reconstruct: identifies what they could have done differently.'),
    P('R — Reflect: places meaning on the experience — insight comes from here.'),
    P('R — Redirect: relates the lesson to other experiences and future lessons.'),
    A('Maneuver / Procedure Grades'),
    P('Describe → Explain → Practice → Perform.'),
    P('Describe: knows the elements, needs help executing. Explain: understands concepts, still needs help. Practice: plans and executes, assistance corrects deviations. Perform: identifies and corrects their own errors — no instructor needed.', 3),
    A('Assessing Risk Management Skills'),
    P('Explain → Practice → Manage/Decide.'),
    P('Manage/Decide = gathers the important data, identifies courses of action, evaluates the risk in each, and makes the appropriate decision — without help.', 3),

    H('Choosing & Structuring Assessment — FI.I.D.K4'),
    P('Determine level-of-learning objectives → list indicators of desired behavior → establish criterion-based objectives → develop criterion-referenced items.'),
    A('Types of Assessments — WAC'),
    P('W — Written: MC, matching, true/false.'),
    P('A — Authentic: real-world tasks (checkrides).'),
    P('C — Collaborative: open-ended questions using HOTS — improves ADM.'),

    S('The Art of Critique'),
    H('Critique — FI.I.D.K5'),
    P('Instructor-to-learner feedback paired with an assessment — covers good AND bad, the parts and the whole.'),
    A('Six types of critique'),
    P('Instructor/learner critique · Learner-led · Small group · Critique by another learner (correct it if it\'s wrong) · Self-critique · Written (gives the learner a copy to keep).'),
    A('Ground rules'),
    P('Stay inside the scheduled time. Cover at most 4–5 correction points. Leave time for a summary. Avoid absolute statements, avoid controversies and taking sides, never get maneuvered into defending a criticism. Written must match oral.'),
    B('Goal: the learner leaves knowing exactly what to improve — and confident they can.'),

    H('Oral Assessment & Questioning — FI.I.D.K6'),
    P('Direct questioning — the most common assessment there is. Reveals effectiveness, checks retention, keeps heads in the game, and identifies what needs re-emphasis.'),
    A('Effective questions — CAB CAP'),
    P('C — Clear and definite · A — Apply to the lesson (relevant) · B — Brief and concise · C — Center on one idea · A — Adapted to the student\'s experience · P — Present a challenge.'),
    A('Questions to avoid — TOP BIT'),
    P('T — Toss-up (two viable options, yes/no) · O — Oversize (too broad) · P — Puzzling (too many parts) · B — Bewildering (hard to even read) · I — Irrelevant · T — Trick questions.'),
    A('Answering learner questions'),
    P('Understand the question → give a direct answer → verify they are satisfied.'),
    B('Action: if you do not know — "great question, let me find out and get back to you." Never bluff.', 3),

    S('Assessing Piloting Ability'),
    H('In Flight and After — FI.I.D.K7'),
    A('During flight'),
    P('Assess against the established standards for THAT learner\'s stage.'),
    B('Action: when it is safe, let the mistake develop and assess their correction — that is where the learning is.', 3),
    A('Postflight evaluation'),
    P('Keep the learner informed of progress every single lesson; with SBT, use collaborative assessment when a scenario completes.'),
    A('Solo flight'),
    P('Positive, confidence-building experience. Instructor present and available, portable radio if possible, comms to a minimum — never talk on short final. Debrief right after and reinforce correct procedures.'),
    A('Practical test recommendations'),
    B('A serious instructor responsibility: your signature says this pilot is safe and competent — they resemble you and your training.'),

    S('Conclusion'),
    P('Review: FAST COCO → V CROUD → authentic (RRRR, Describe/Explain/Practice/Perform) → WAC → critique types and ground rules → CAB CAP vs TOP BIT → assessing ability through solo and recommendation.'),
    P('Assessment is not the report card at the end — it is the steering wheel of the whole course.'),
  ]};

  /* ============================================================
     I.E — Effective Teaching in a Professional Environment
     Acronym spine: MACKBAG · SAD PP
     ============================================================ */
  window.CFI_SCRIPTS['i-e-effective-teaching-pro-env'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — the instructor is the central figure in aviation training; the student\'s habits will look like yours.'),
    H('Overview'),
    P('Aviation instructor responsibilities (incl. MACKBAG) → flight instructor responsibilities → qualifications & professionalism (SAD PP) → professional development → ethics and conduct.'),
    H('What'),
    P('What the FAA — and your learners — expect from you as a professional educator.'),
    H('Why'),
    P('You lay the foundation for someone\'s entire aviation career. Professionalism is not optional equipment.'),

    S('How:'),

    H('Aviation Instructor Responsibilities — FI.I.E.K1'),
    A('Helping learners learn'),
    P('Learning should be interesting AND enjoyable — make it beneficial and fun; measure against standards.'),
    A('Providing adequate instruction'),
    P('Analyze each learner\'s personality, thinking, and ability, then tailor.'),
    P('Slow progress: assign easier sub-goals to rebuild momentum. Fast progress: watch for the belief that error-correction no longer matters. Complex tasks: break into elements, practice each, then recombine.', 3),
    A('Training to established standards'),
    B('Letting substandard performance slide fails the student — strive for excellence, hold the line.'),
    A('Emphasizing the positive'),
    P('Positive instruction results in positive learning — make the first lessons enjoyable; they set the tone (Law of Primacy).'),
    A('Ensuring aviation safety'),
    P('Teach safety habits, risk management, and decision-making from day one — students copy what they see you do.'),
    A('Minimizing learner frustration — MACKBAG'),
    P('M — Motivate students.'),
    P('A — Approach learners as individuals — every personality is different.'),
    P('C — Constructive criticism, never ridicule.'),
    P('K — Keep learners informed of their progress.'),
    P('B — Be consistent — same checklists, same standards, every time.'),
    P('A — Admit when you are wrong; we all make mistakes.'),
    P('G — Give credit when due — praise, but do not water it down by overusing it.'),

    H('Flight Instructor Responsibilities — FI.I.E.K2'),
    P('Mold a safe pilot with a professional approach to aviation.'),
    A('Ensuring learner skill set'),
    P('You decide when they are ready to solo — they must consistently prove the maneuvers on their own.'),
    A('Physiological obstacles for flight learners'),
    P('Strange noises, G-forces, motion sickness, fear of small airplanes — never ignore or ridicule; most are overcome once the learner understands the cause.'),
    A('Endorsements & recommendations'),
    P('Knowledge tests, practical test recommendations, retesting after failure, solo endorsements — each one is your name on their readiness.'),
    A('See and avoid'),
    B('Action: your eyes stay OUTSIDE while the student performs the maneuver.'),
    A('Currency vs. proficiency'),
    P('Currency = the FAA bare minimums. Proficiency = recent enough practice to be genuinely safe and competent. Teach learners to chase proficiency.'),
    A('Supervision & surveillance'),
    P('Supervise solos and cross-countries, and supervise the overall progress of training.'),

    H('Qualifications & Professionalism — SAD PP — FI.I.E.K3'),
    P('Stay thoroughly familiar with every instrument, avionics unit, and system you teach in; stay current on certification requirements.'),
    A('S — Sincerity'),
    P('Straightforward and honest, always.'),
    A('A — Acceptance of the learner'),
    P('Accept them as they are — acceptance rather than ridicule.'),
    A('D — Demeanor'),
    P('Your attitude and behavior build (or wreck) the professional image — the vibe you radiate is part of the instruction.'),
    A('P — Personal appearance and habits'),
    P('Neat, clean, dressed to be taken seriously. Hygiene matters in a small cockpit.'),
    A('P — Proper language'),
    P('Speak positively and descriptively; keep the profanity out of the cockpit.'),

    H('Professional Development — FI.I.E.K4'),
    P('Do not go complacent — keep improving your qualifications and freshening your material.'),
    P('Continuing education: seminars, workshops, the WINGS program.'),
    P('Reflective teaching: keep asking what YOU could have taught better.'),
    P('Maintain a library of current procedures and publications.'),
    P('Additional ratings — and the Gold Seal Flight Instructor Certificate.'),

    H('Instructor Ethics & Conduct — FI.I.E.K5'),
    P('The Flight Instructor\'s Model Code of Conduct (FIMCC):'),
    P('Make safety the number one priority · Develop and exercise good judgment · Recognize and manage risk · Be accountable for your actions · Act with responsibility and courtesy · Adhere to prudent operating practices · Adhere to applicable laws and regulations.'),

    S('Conclusion'),
    P('Review: responsibilities (MACKBAG for frustration) → flight-instructor duties (skill set, endorsements, see-and-avoid, currency vs proficiency) → SAD PP professionalism → development → FIMCC ethics.'),
    P('The through-line: your students become the kind of pilot you model, not the kind you describe.'),
  ]};

  /* ============================================================
     I.F — Effective Teaching: Risk Management & Accident Prevention
     Acronym spine: PAVE · TEAM · 5 P's · FRAT · DECIDE · MIRIA
     ============================================================ */
  window.CFI_SCRIPTS['i-f-effective-teaching-rm'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — a brand-new private pilot from a sleepy Texas gulf strip rents a plane in Denver\'s Bravo in mid-summer. Nothing is broken — and everything is risky. That is what this lesson is for.'),
    H('Overview'),
    P('RM principles → the 3-step process (Identify-PAVE, Assess-matrix, Mitigate-TEAM) → tools (PAVE deep dive, 5 P\'s, FRAT) → teaching RM by phase → managing risk while instructing → ADM (DECIDE), obstacles to SA, hazardous attitudes (MIRIA), SRM/CRM.'),
    H('What'),
    P('How to identify, assess, and mitigate risk — and how to teach learners to do it instinctively.'),
    H('Why'),
    B('Teaching learners to recognize and mitigate risk is the single most safety-critical thing an instructor does.'),

    S('How:'),

    H('Principles of Risk Management — FI.I.F.K1'),
    P('Accept no unnecessary risk · Make risk decisions at the appropriate level · Accept risk only when benefits outweigh costs · Integrate RM into planning at ALL levels.'),

    H('The 3-Step Risk Management Process'),
    A('1 — Identify the hazard (PAVE)'),
    P('A hazard is any real or potential condition that can cause injury, illness, death, or damage — find them with the PAVE checklist.'),
    A('2 — Assess the risk'),
    P('How LIKELY is the loss, and how SEVERE would it be? Plot it on the risk assessment matrix (likelihood × severity).'),
    A('3 — Mitigate the risk (TEAM)'),
    P('T — Transfer it · E — Eliminate it · A — Accept it (when benefits outweigh) · M — Mitigate what remains.'),
    P('Cancel, reroute, delay — or for the Denver scenario: bring an experienced CFI and get checked out in the airspace.', 3),

    H('Risk Management Tools — PAVE — FI.I.F.K2'),
    A('P — Pilot'),
    P('Am I personally ready for this flight? Run IMSAFE: Illness, Medication, Stress, Alcohol, Fatigue, Emotion.'),
    A('A — Aircraft'),
    P('Is this aircraft suitable? Airworthy (ARROW documents), equipped for the mission (IFR?), maintenance current.'),
    A('V — enVironment'),
    P('Weather, terrain, airports — brief it with NWKRAFT: NOTAMs, Weather, Known ATC delays, Runway lengths, Alternates, Fuel, Takeoff/landing distances.'),
    A('E — External pressures'),
    B('The killer: would I still go if this pressure did not exist? If no — do not go. Get-there-itis has no place in a training airplane.'),
    A('The 5 P\'s — in-flight decision points'),
    P('Plan (weather, route, fuel — it keeps changing; adjust with it) · Plane (condition, equipment, automation) · Pilot (IMSAFE again, in flight) · Passengers (their wants pressure your decisions — you are PIC) · Programming (set up avionics ahead of time; know when NOT to be heads-down).'),
    A('Flight Risk Assessment Tool (FRAT)'),
    P('A scored questionnaire that turns risk into a number and a go/no-go picture.'),
    P('Roughly: ≤10 low risk · 11–20 exercise caution · 21–30 area of concern.', 3),

    S('Teaching & Managing Risk'),
    H('Teaching Risk Management — FI.I.F.K3/K4'),
    B('Introduce RM at the very beginning of training — it is a practice woven into every flight, never a separate subject.'),
    B('Action: learners need to SEE you practicing RM — model it, then hand them the lead.'),
    A('Techniques by phase of instruction'),
    P('Pre-solo: RM discussion in preflight and postflight briefings; FRAT before each solo.'),
    P('Post-solo / pre-XC: learner performs some of the assessment; FRAT plus discussion.'),
    P('Cross-country: learner runs the full risk analysis before every flight and reviews it with you.'),
    P('Instrument: weather and avionics familiarity dominate — hard IMC in a six-pack is not hard IMC in a G1000.'),
    P('Flight review / recurrency: it has probably been a while — build scenarios that fit the pilot they actually are; no hard-IMC scenarios for a crop duster.'),
    H('Managing Risk During Flight Instruction — FI.I.F.K5'),
    P('Same tools, applied to the instructional flight itself — run PAVE with the learner involved in every step.'),
    P('Pilot: qualification and IMSAFE risks — for BOTH of you. Aircraft: maintenance, right plane for the job. enVironment: collision hazards, terrain, busy airspace. External: squeezing flights into busy schedules and weather windows.', 3),
    A('Takeoff & landing special considerations — low and slow'),
    B('Action: set a limit of error — how far you let the learner deviate before you intervene. It gives them room to fix their own mistakes and you time to recover.'),
    P('Do not practice near YOUR personal minimums. Teach before calling tower, not during high-focus moments. Anticipate the likely landing errors before they happen — crosswinds, low approach speeds.'),

    S('ADM & Human Factors'),
    H('Aeronautical Decision Making — FI.I.F.K6'),
    P('A systematic approach to consistently determine the best course of action for the circumstances.'),
    A('The DECIDE model'),
    P('D — Detect a problem (make sure it IS one) · E — Estimate the need to react · C — Choose a desirable outcome · I — Identify solutions · D — Do the action · E — Evaluate its success.'),
    H('Obstacles to Situational Awareness — FI.I.F.R2'),
    P('Distractions: a big factor in accidents — always fly the airplane first.'),
    P('Fatigue: less alert, worse performance — the only real remedy is sleep.'),
    P('Complacency: overconfident and hard to recognize.'),
    B('Action: probe complacency — ask for the position of other traffic in the pattern, or hand them a made-up problem and watch their SA.', 3),
    H('Hazardous Attitudes & Antidotes — MIRIA — FI.I.F.R3'),
    A('M — Macho: "watch this"'),
    P('Antidote: taking chances when flying is foolish.'),
    A('I — Impulsivity: reacting without thinking'),
    P('Antidote: not so fast — think first.'),
    A('R — Resignation: "what\'s the use, I give up"'),
    P('Antidote: I am not helpless; I can make a difference.'),
    A('I — Invulnerability: "that happens to other people"'),
    P('Antidote: it could happen to me.'),
    A('A — Anti-authority: "don\'t tell me what to do"'),
    P('Antidote: follow the rules — they are usually right.'),
    B('Recognize the thought, name it, apply the antidote — teach learners to do this out loud at first.'),
    H('Stress & Resource Management'),
    P('Good stress: moderate, keeps the learner on high alert, improves skill — dose it to their level and push limits slightly.'),
    P('Bad stress: beyond their skill level — skills deteriorate fast.'),
    A('SRM / CRM'),
    P('How to gather information, analyze it, and decide — CRM adds the team: dispatchers, other pilots, cabin, maintenance, ATC.'),
    P('Use of resources: every available one — weather sources, ATC, performance sheets, equipment.', 3),
    P('Workload management: plan, prioritize, and sequence to stay ahead; prepare for high-workload phases BEFORE they arrive; recognize the pile-up (busy airspace, strong tailwind, tasks stacking).', 3),

    S('Conclusion'),
    P('Review: principles → Identify (PAVE) / Assess (matrix) / Mitigate (TEAM) → 5 P\'s and FRAT → teach RM from day one and by phase → limit-of-error while instructing → DECIDE, SA obstacles, MIRIA antidotes, SRM/CRM.'),
    P('The instructor\'s job: teach, practice, model, and coach risk management until the learner does it without being asked.'),
  ]};

})();
