/* custom.js — hand-authored scripts that survive build.py rebuilds.
   Loaded after data.js.

   window.CFI_SCRIPTS[lessonId] = { nodes: [...] }
     Seeds the "My Script" tab for that lesson with a pre-written teaching script.
     Every line stays editable / removable / note-able in the app.
     Node shape: { t: text, l: level (-1 section, 0 header, 1+ indent), b: bold }
*/
(function () {
  const S  = t => ({ t, l: -1, b: true });          // orange section
  const H  = t => ({ t, l: 0,  b: true });          // blue header
  const A  = t => ({ t, l: 1,  b: true, k: true }); // acronym letter / topic (k = force topic style)
  const P  = (t, l) => ({ t, l: l || 2, b: false }); // talking point
  const B  = (t, l) => ({ t, l: l || 2, b: true });  // emphasised point

  window.CFI_SCRIPTS = window.CFI_SCRIPTS || {};

  /* ============================================================
     I.A — Effects of Behavior & Communication on the Learning Process
     Flow follows the FIA Task A video; spine is the acronyms;
     detail augmented from the Backseat teach script + extra detail.
     ============================================================ */
  window.CFI_SCRIPTS['i-a-behavior-com-on-learning'] = { nodes: [

    S('Introduction'),
    H('Attention'),
    P('Every learner acts and reacts differently, which is why we as instructors need to understand human behavior and communicate in a way that actually lands.'),
    H('Overview'),
    P('Human behavior & motivation'),
    P('Human needs (PSBECS)'),
    P('Defense mechanisms (DR DR F CPR)'),
    P('Learner struggles — anxiety, stress, impatience'),
    P('Effective communication (SSR · COIL · LIQIR)'),
    H('What'),
    P('How human behavior — needs, personalities, motivation, emotions, age — and communication affect the learning process.'),
    H('Why'),
    P('Learning is a change in behavior as a result of experience. To cause that change I have to know why people act the way they do.'),
    B('Self-application: once you can name your own defense mechanisms and motivators, you use this every day — that is what makes the FOI worth learning instead of dreading.'),

    S('How:'),

    /* ---------------- foundations ---------------- */
    H('Foundations of Human Behavior — FI.I.A.K1a'),
    A('Two definitions of human behavior'),
    P('1. The factors that cause people to act in predictable ways — behavior is a product of experience.'),
    P('Ex: how two learners take praise after a good landing — one relaxes into it, the other gets complacent — depends on how praise landed for them long before they met me.', 3),
    P('2. The attempt to satisfy human needs — simple (food, water) through complex (respect, acceptance).'),
    A('Life course of humans'),
    P('As people mature they move from dependency toward self-direction, so the age of the learner shapes how I design the curriculum.'),
    B('Big picture: a working knowledge of behavior helps me understand the learner — that is the whole point of this task.'),

    H('Instructor & Learner Relationship — FI.I.A.K1b'),
    P('Everyone has an individual style of learning; working with that style benefits both of us.'),
    P('The match — or mismatch — between my teaching style and their learning style drives instructional satisfaction.'),
    B('My job is two-part: identify MY teaching style, identify THEIR learning style, and meet in the middle.'),
    P('I think out loud through every maneuver; a quiet, methodical learner needs the whiteboard and ten seconds of silence to process the exact same thing.', 3),
    P('RM — Recognizing & Accommodating Human Behavior (FI.I.A.R1): adjust for different personalities, motivators, and learning styles.'),

    /* ---------------- motivation ---------------- */
    H('Motivation — FI.I.A.K1c'),
    P('The driving force a person feels when trying to accomplish a goal; it lies at the heart of goals and is likely the dominant force governing progress.'),
    B('There is always an exchange — five a.m. drives and $200 an hour, traded for the right seat.'),
    A('Motivation can be positive or negative, tangible or intangible, subtle or obvious'),
    P('Positive — awards, recognition, tangible returns, group belonging, favorable self-image, a safe and pleasant environment.'),
    P('Positive is almost always the better choice.', 3),
    P('Negative — threats, fear, criticism. May work short term, but creates insecure training, inhibits learning, and damages the relationship.'),
    P('Avoid it with everyone except the most overconfident and impulsive learner.', 3),
    A('Maintaining motivation'),
    P('Praise incremental successes and tie each accomplishment back to the lesson objective; keep presenting new challenges.'),
    P('Drops are natural once the initial excitement wears off — remind them of their goals and normalize plateaus.'),
    B('Takeaway: identify how this learner is motivated, then use it to keep them moving.'),

    /* ---------------- maslow ---------------- */
    H('Human Needs — Maslow\'s Hierarchy: PSBECS — FI.I.A.K1d'),
    P('Levels of importance. Until the lower needs are met, the higher ones cannot be — and the learner is not ready to learn.'),
    A('P — Physiological'),
    P('Biological needs: food, rest, water, protection from the elements.'),
    P('A learner who came straight off a ten-hour shift without eating spends the lesson thinking about food, not about pitch and power.', 3),
    P('Get ahead of it — food, water, and a bathroom stop before we walk out, instead of burning their money in the air.', 3),
    A('S — Safety & Security'),
    P('Protection against danger, threats, and deprivation — at home and in the airplane.'),
    P('An airplane they overheard getting squawked yesterday: they will spend the hour listening to the engine instead of flying it.', 3),
    A('B — Belonging'),
    P('The need to associate, and to give and receive friendship — loneliness and alienation are real at an unfamiliar flight school.'),
    P('Counter: the learner who only trains at odd hours and never meets anybody quietly decides they do not belong here — introduce them around and get them a study partner.', 3),
    A('E — Esteem'),
    P('Internal (self-esteem): confidence, independence, achievement, competence.'),
    P('External (reputation): status, recognition, appreciation, respect of associates.'),
    P('High esteem · confident, independent, motivated. Low esteem · insecure, quicker to quit on a problem.', 3),
    P('The learner who apologizes after every single landing is telling me their esteem needs work before their technique does.', 3),
    B('If esteem is not met they are not ready to learn — build them up and push them out of the comfort zone.', 3),
    A('C — Cognitive & Aesthetic (added years after the original theory)'),
    P('Cognitive: the need to know and understand — understanding lets them control the situation and make informed decisions.'),
    P('Say "lean the mixture" and it is gone by next lesson; show them a fouled plug and what detonation does to a piston and they never skip it again.', 3),
    P('Aesthetic: emotional needs — can they see the beauty in what they are learning? Do they enjoy the school, the airplane, the flying?'),
    B('The part I control: three hours in a hot cockpit beside someone who sighs at every mistake is unbearable — nobody learns in that seat. If an instructor dislikes a learner, it affects the ability to teach.', 3),
    A('S — Self-Actualization'),
    P('Realizing one\'s own potential; reachable only when every other need is satisfied.'),
    B('I cannot make anyone self-actualize — but I control everything underneath it, so I clear the path and create the opportunity.', 3),
    P('Law of Readiness ties it together: the learner must be physically and mentally ready. Verify readiness every lesson (IMSAFE + motivation techniques).'),

    /* ---------------- defense mechanisms ---------------- */
    H('Defense Mechanisms — DR DR F CPR — FI.I.A.K1e'),
    P('Subconscious, almost automatic, ego-protecting reactions to unpleasant situations — used to soften failure, relieve guilt, and protect self-worth.'),
    B('Why I care: spotting one tells me the learner is frustrated or uncomfortable, so I can defuse the cause instead of arguing with the reaction.'),
    A('D — Denial'),
    P('Refusal to accept reality because it is too threatening.'),
    P('I tell them they lost 300 feet in the steep turn and they answer, "no, I was within a hundred the whole way around."', 3),
    A('R — Repression'),
    P('Uncomfortable thoughts pushed into inaccessible areas of the unconscious mind.'),
    P('At debrief they cannot recall one thing about the go-around we just flew — the part that scared them is simply gone.', 3),
    A('D — Displacement'),
    P('Unconscious shift of emotion from the original object to a less threatening substitute.'),
    P('Frustrated in the pattern, and on the walk back in it is the airplane, the dispatcher, and the schedule that are the problem.', 3),
    B('I have full authority to say: "you seem frustrated — I am not comfortable flying right now." Use it.', 3),
    A('R — Rationalization'),
    P('Subconscious justification of actions that would otherwise be unacceptable; they sincerely believe the excuse.'),
    P('"These radios are junk" — after missing two calls because they were behind the airplane.', 3),
    A('F — Fantasy'),
    P('Daydreaming about how things should be rather than doing something about how they are.'),
    P('Dangerous: they can become satisfied with the daydream and stop chasing the goal — the whole debrief is about which airline they will fly for, not the three landings we need to fix.', 3),
    A('C — Compensation'),
    P('Disguising a weak quality by emphasizing a more positive one; may substitute an easier goal for the preferred one.'),
    P('"My landings are rough, but nobody in the class works the radio like I do."', 3),
    A('P — Projection'),
    P('Blame relegated to others for their own shortcomings and mistakes.'),
    P('"You never showed me that" — about the checklist flow we ran together the last two lessons.', 3),
    A('R — Reaction Formation'),
    P('Protecting against a dangerous desire by developing the opposite attitude — accepting or reacting opposite of the truth to avoid discomfort.'),
    P('White knuckles and a shaky voice after the unusual attitude recovery, and when I ask, they laugh and say that was fun. Consider ending the lesson right there — nothing more is going in.', 3),
    P('Non-aviation: insisting you were never that interested in the job you just got rejected from.', 3),
    A('Dealing with defense mechanisms'),
    B('Never confront the mechanism directly — that makes them more defensive. Create an environment where they do not need to defend themselves and address the root cause.'),

    /* ---------------- learner struggles ---------------- */
    S('Learner Struggles — Emotional Reactions (FI.I.A.K2)'),
    P('Analyze the learner\'s behavior before, during, and after every lesson so problems get identified and solved.'),
    H('Anxiety — FI.I.A.K2a'),
    P('"A state of mental uneasiness arising from fear" — the most significant psychological factor affecting flight instruction.'),
    P('Why: flying is threatening to the unfamiliar, and fear of falling is nearly universal.'),
    P('Reactions: hesitancy to act, the impulse to do something even if wrong, or freezing.'),
    P('Watch for it at: first flight, first solo, solo cross-countries, checkrides.'),
    P('Counter: normalize the feeling, reinforce enjoyment of flying, teach them to cope, and rebuild confidence — I would not sign them off unready.'),
    B('Never say "do not mess up my pass rate."'),
    H('Stress — FI.I.A.K2a'),
    P('The body\'s response to high demand.'),
    B('Low stress improves performance; high stress significantly degrades it. Finding that line per learner is the craft.'),
    P('Normal reactions: fast, accurate responses within the limits of their experience and training.'),
    P('First few landing lessons — I work the radio so their whole brain can go to the picture out the window.', 3),
    P('Two weeks from the checkride at a busy Class D — they work the radio, spot the traffic, and land it while I stay quiet.', 3),
    A('Abnormal reactions to stress (this one is about MY safety)'),
    P('Random, illogical, absent, or inadequate responses; over-cooperation, extreme self-control, inappropriate laughter or singing, rapid emotional shifts.'),
    P('If it concerns me: get on the ground and defuse the situation.'),
    P('After: refrain from instructing them, arrange an evaluation flight with a second instructor, and report to the FAA if serious psychological issues are at play.'),
    B('DO NOT ENDORSE THEM — I am liable.'),
    H('Impatience — FI.I.A.K2b'),
    P('Seeks the ultimate objective without considering the means — the learner who wants to solo by hour twelve and treats slow flight as a speed bump.'),
    P('Counter: present training one step at a time with clearly stated goals, tailored to their pace. Visible progress is what keeps them.'),
    H('Worry or Lack of Interest — FI.I.A.K2c'),
    P('Those worried or emotionally upset are not ready to learn and get little from instruction.'),
    P('Counter: divert attention from the worry to the task at hand.'),
    P('Prevent: make sure they know exactly how they progressed and what is deficient — say nothing about their landings and a worrier decides they were terrible.'),
    P('For lack of interest: remind them of the goals they told me on day one.'),
    H('Physical Discomfort, Illness, Fatigue & Dehydration — FI.I.A.K2d'),
    P('All slow the rate of learning and should be mitigated — run PAVE / IMSAFE. Ties straight back to physiological, the base of PSBECS.'),
    P('Fatigue is one of the most treacherous hazards to flight safety; it impairs judgment and decision making.'),
    P('Acute: normal part of everyday living. Chronic: physiological/psychological problems — do not fly.', 3),
    P('Dehydration reduces alertness; heatstroke is the body failing to control temperature. Carry water, keep it cool, wear light clothing.'),
    H('Apathy Due to Inadequate Instruction — FI.I.A.K2e'),
    P('Provide well-planned, accurate, meaningful instruction taught to the level of the learner.'),
    B('Let the ego go. Be vulnerable and own what I do not know — "great question, I am not sure; let me find out and get back to you."'),
    P('Pretend to know everything, get fact-checked once, and they will not believe anything I say afterward.'),
    P('Once the instructor loses their confidence it is very hard to regain, and learning is diminished.'),
    P('Bonus: "I stumped the CFI" sparks a competitive fire that pushes us both.', 3),
    H('Teaching the Adult Learner — FI.I.A.K3'),
    P('Most student pilots are adults: autonomous and self-directed, goal and relevancy oriented, practical, drawing on a foundation of life experience, and needing to be shown respect.'),
    P('They may be slower to grasp a brand-new concept than a younger learner — the same reason a new language comes easier at ten than at forty.'),
    P('So I: clarify expectations early, use an organized syllabus with clear objectives, let them control pace, use scenario-based training, connect new ideas to what they know, and refrain from spoon-feeding.'),

    /* ---------------- communication ---------------- */
    S('Effective Communication — FI.I.A.K4'),
    P('It does not happen automatically — I have to develop a style that actually conveys information.'),
    P('Communication takes place when a person transmits ideas or feelings to another; its effectiveness is measured by how closely the idea received matches the idea sent.'),
    B('Goal: a change in behavior.'),
    H('Basic Elements — SSR — FI.I.A.K4a'),
    A('S — Source (the sender, speaker, transmitter — me)'),
    P('Effectiveness rests on three factors: ability to select and use language, revealing a positive attitude about self and material, and material that is accurate, current, and stimulating.'),
    A('S — Symbol (the words, signs, or oral/visual/tactile codes carrying the message)'),
    P('Choose the symbols best for opening, explaining, clarifying, emphasizing, and closing — and the medium best suited to carry them.'),
    P('Monitor feedback; if it is not landing, change the symbol — a traffic pattern described out loud is a blur, drawn on the whiteboard it is obvious.', 3),
    P('Learners need feedback on how they are doing; deliver negative feedback in private only.'),
    A('R — Receiver (the listener, reader, learner)'),
    P('Communication is effective when the receiver reacts with understanding and changes behavior accordingly.'),
    P('Not everyone learns the same way — using multiple approaches is most effective.'),
    H('Barriers to Effective Communication — COIL — FI.I.A.K4b / R2'),
    A('C — Confusion between the symbol and the symbolized object'),
    P('The meaning or intent of the words, or the context, is not clear — sarcasm, or a word with two meanings.'),
    P('"Level off" — do they stop the climb, or roll the wings level?', 3),
    A('O — Overuse of Abstractions'),
    P('Abstractions are general rather than specific words; they may not evoke the same experience in the learner\'s mind.'),
    P('"Slow it down" on final — pitch, power, or flaps? Say "1500 RPM and 65 knots" instead.', 3),
    A('I — Interference'),
    P('The message gets disrupted or truncated — confirm it was understood.'),
    P('External factors outside my control: physiological (injury, hearing loss), environmental (noise, radio static, busy frequency), psychological (fear, mistrust).'),
    P('Prior learning interferes too — years of driving says steer with your hands, so the yoke fights them all the way down the taxiway.', 3),
    A('L — Lack of Common Experience'),
    B('The greatest single barrier to effective communication.'),
    P('I must speak the same language as the learner; when specific terminology is required, confirm they understand it.'),
    P('"Make short approach," "squawk VFR," "expedite" — obvious to me, noise to a ten-hour student unless I brief the words on the ground.', 3),
    P('Generational gap between a young CFI and an adult learner counts here too.', 3),
    H('Developing Communication Skills — LIQIR — FI.I.A.K4c'),
    A('L — Listening'),
    P('Listen actively and listen to understand rather than to refute — notes, eye contact, and hear the question they are actually asking.'),
    A('I — Instructional Communication'),
    P('Know the topic cold and be confident; use stories and past experience to illustrate points and hold attention; evaluate to confirm the level of understanding.'),
    A('Q — Questioning'),
    P('Good questioning determines how well the learner understands. Ask open-ended, focused questions; paraphrase and perception-check to confirm.'),
    A('I — Instructional Enhancement'),
    P('The deeper my knowledge of an area, the better I convey it — and the more confident and efficient I am.'),
    B('If I cannot explain it simply, I do not understand it well enough yet.', 3),
    A('R — Role Playing'),
    P('Practice instructing to build the skill; play ATC for the learner so the radios stop being a threat and their confidence builds before the real thing.'),

    S('Conclusion'),
    P('Brief review: foundations · motivation · PSBECS · DR DR F CPR · learner struggles · SSR / COIL / LIQIR.'),
    P('Tie back to why: every one of these is a tool for spotting what is blocking the learner and removing it.'),
  ]};

  /* ============================================================
     I.B — Learning Process
     Acronym spine: A MAP · RIC · G-STEP · MUA · REEPIR · CAP
     (RUAC/ARVOI/OIPH) · CTE · CAAR · DBR · SM · CULT DR ·
     FIRRS · MALAMP
     ============================================================ */
  window.CFI_SCRIPTS['i-b-learning-process'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('Everything we teach has to actually stick, which is why we as instructors need to understand how people learn in the first place.'),
    H('Overview'),
    P('Definition & characteristics of learning (A MAP / RAMP)'),
    P('Learning theory — behaviorism & cognitive (RIC)'),
    P('Perceptions & insight (G-STEP)'),
    P('Acquiring knowledge (MUA) & laws of learning (REEPIR)'),
    P('Domains of learning (CAP)'),
    P('Acquiring skills (CAAR) & practice (DBR)'),
    P('Errors (SM · CULT DR)'),
    P('Memory, forgetting (FIRRS), retention (MALAMP), transfer'),
    H('What'),
    P('Understanding how people learn and applying that knowledge to the learning environment.'),
    H('Why'),
    P('Effective teaching starts with knowing how learning actually works — the subject, the learner, and the process.'),

    S('How:'),

    H('Definition of Learning — A MAP — FI.I.B.K1'),
    A('A — A change in behavior as a result of experience'),
    P('The core definition: relatively permanent change in behavior or cognition resulting from experience.'),
    A('M — Multifaceted'),
    P('Involves verbal, conceptual, perceptual, motor, problem-solving, and emotional elements all at once.'),
    A('A — Active process'),
    P('The learner has to DO something with the material — you cannot pour knowledge into a passive student.'),
    A('P — Purposeful'),
    P('Each learner has their own goals; learning sticks when it connects to what THEY are trying to accomplish.'),
    B('Same four ideas = "Characteristics of Learning (RAMP)": Result of experience, Active, Multifaceted, Purposeful. One list, two acronyms — know both names.'),

    H('Learning Theory — Behaviorism & Cognitive (RIC) — FI.I.B.K2'),
    A('Behaviorism'),
    P('Behavior can be predicted and shaped by reward and punishment (Pavlov\'s dog).'),
    P('Popularity has waned — learning is more complex than stimulus and response.', 3),
    B('Keep its best principle: immediate, specific positive reinforcement when the learner does something right.', 3),
    A('Cognitive Theory — the three branches RIC'),
    P('Focuses on what happens inside the learner\'s mind: how the brain observes, learns, problem-solves, decides.'),
    P('R — Reflective Thought Theory: learning develops from reflection.', 3),
    B('Action: spark reflection by having the learner self-critique the flight during the debrief.', 3),
    P('I — Information Processing Theory: the brain processes, stores, retrieves, and applies information like a computer.', 3),
    P('C — Constructivism: learners build new understanding on top of old experience — teach high-to-low pressure before teaching lift.', 3),

    S('Perception to Understanding'),
    H('Perceptions & Insight — FI.I.B.K3'),
    A('Perceptions'),
    P('All initial learning comes from perceptions, received through the five senses — most through sight (~75%).'),
    B('Action: teach multi-sensory whenever possible; combining senses accelerates learning.'),
    A('Insight'),
    P('When perceptions come together into a meaningful whole — the "aha" moment.'),
    P('Stall example: engine quiets + airspeed decays + buffet in the seat = all those perceptions click into "we are about to stall."', 3),
    H('Factors That Affect Perception — G-STEP'),
    A('G — Goals & Values'),
    P('Every experience is filtered through the person\'s beliefs and values.'),
    P('A CFI who sees the job as hour-building teaches and perceives differently than one who is there to make a difference.', 3),
    A('S — Self-Concept'),
    P('Self-image drives openness: a confident learner stays open to new experiences; an insecure one may quit when it gets tough.'),
    A('T — Time & Opportunity'),
    P('Learning takes proper sequence AND enough time — airspace, taxi, landings, and patterns come before anyone talks about solo.'),
    A('E — Element of Threat'),
    P('Threat narrows perception to tunnel vision on whatever is threatening.'),
    P('Alternator light flashes red — breaker reset, all good — but the student keeps staring at that corner of the panel.', 3),
    A('P — Physical Organism'),
    P('The body is the perceptual apparatus; it has to work. A plugged nose cannot smell the electrical fire before it is visible.'),

    H('Acquiring Knowledge — MUA — FI.I.B.K4'),
    A('M — Memorize'),
    P('Learners memorize facts first, before real understanding exists.'),
    A('U — Understand'),
    P('The memorized pieces get organized into how things actually work.'),
    A('A — Application'),
    P('Using that understanding to solve real problems — the level you actually fly at.'),

    H('Laws of Learning — REEPIR — FI.I.B.K5'),
    A('R — Readiness'),
    P('Basic needs met = mentally, physically, emotionally ready. Ties straight to Maslow and IMSAFE.'),
    A('E — Effect'),
    P('Pleasant or satisfying feelings strengthen learning; frustration and fear weaken it.'),
    A('E — Exercise'),
    P('Practice makes permanent — use it or lose it.'),
    A('P — Primacy'),
    B('What is learned FIRST creates a near-unshakable impression — so teach it right the first time; unteaching is far harder than teaching.'),
    A('I — Intensity'),
    P('An engaging, vivid lesson sticks; a dull one does not. The real airplane beats the whiteboard.'),
    A('R — Recency'),
    P('The most recently learned is best remembered — why we debrief immediately, and why checkride prep reviews everything.'),

    H('Domains of Learning — CAP — FI.I.B.K6'),
    A('C — Cognitive Domain (knowledge) — RUAC'),
    P('Rote · Understanding · Application · Correlation.'),
    P('Rote: recites V-speeds. Understanding: knows why. Application: uses them in the flare. Correlation: connects gusty winds to adding half the gust factor without being told.', 3),
    A('A — Affective Domain (attitudes/feelings) — ARVOI'),
    P('Awareness · Response · Value · Organize · Integrate.'),
    P('The safety-culture domain: from hearing about checklist discipline to being someone who would never skip one.', 3),
    A('P — Psychomotor Domain (physical skills) — OIPH'),
    P('Observe · Imitate · Practice · Habituate.'),
    P('Watch me land · follow me through · your landings with my coaching · landings are automatic.', 3),

    H('Scenario-Based Training — CTE — FI.I.B.K8'),
    P('Real-world scenarios that force the learner to problem-solve — SBT is how we build HOTS/ADM.'),
    A('C — Clear objective'),
    P('What do you want to teach and why?'),
    A('T — Tailored to the learner'),
    P('Match the scenario to their skill level.'),
    A('E — Environmental factors'),
    P('A fuel-emergency scenario on the ground gives thinking time; the same problem in the air does not. Choose the environment deliberately.'),

    S('Acquiring Skills'),
    H('Stages of Skill Acquisition — CAAR — FI.I.B.K9'),
    A('C — Cognitive stage'),
    P('Memorizing what to do — thinking through every step of the maneuver.'),
    A('A — Associative stage'),
    P('Can perform the skill and assess their own performance afterward, but it takes focus and effort.'),
    A('AR — Automatic Response stage'),
    P('Performs with little conscious effort, freeing attention for other tasks — radio calls during a landing.'),
    H('Building the Skill'),
    A('Knowledge of results'),
    B('Action: tell learners immediately when they are wrong — never let them practice mistakes.'),
    A('Power Law of Practice'),
    P('Speed and accuracy improve as a power of the number of repetitions — improvement is fast early, slower later.'),
    A('Learning plateaus'),
    P('Learning slows after rapid progress — normal, everyone hits them.'),
    B('Action: normalize the plateau and keep them practicing through it.', 3),
    H('Types of Practice — DBR'),
    A('D — Deliberate (initial)'),
    P('Specific goal, detailed plan, specific feedback.'),
    A('B — Blocked (middle)'),
    P('Same skill over and over until it reaches the automatic response stage.'),
    A('R — Random (final)'),
    P('Mix the skills up — best for retention. This is checkride-prep mode.'),
    H('Evaluation vs. Critique'),
    P('Evaluation: broad assessment of performance — also checks YOUR teaching effectiveness.'),
    P('Critique: monitoring practice and giving feedback so the skill develops correctly — constructive, never ridicule.'),

    S('Attention & Errors'),
    H('Distractions, Interruptions, Fixation & Inattention — FI.I.B.K10'),
    A('Distraction'),
    P('An unexpected event that CAN disrupt attention — passenger asks a question on short final; pilot lands first.'),
    A('Interruption'),
    P('The learner actually diverts attention to it — answers the question and forgets the position call. Distractions become interruptions.'),
    A('Fixation'),
    P('Locking onto one task above all else — instrument students fixating on a single gauge.'),
    A('Inattention'),
    P('Not noticing what is going on around them — fixation leads here: staring at the altimeter, neglecting everything else.'),
    H('Errors — SM — FI.I.B.K11'),
    A('S — Slip'),
    P('Intended one thing, did another — pulls the mixture instead of the throttle. Signals a lack of practice.'),
    A('M — Mistake'),
    P('Did exactly what they intended, and it was wrong — dumps full flaps abeam the numbers. Signals a gap in knowledge.'),
    B('Slip · more practice. Mistake · more teaching. Diagnose which one it was before you fix it.'),
    H('Reducing Errors — CULT DR'),
    P('C — Checking for errors: scan the instruments.'),
    P('U — Using tools: heading bug, altitude bug, timers, checklists, writing things down.'),
    P('L — Learning and practicing — correctly.'),
    P('T — Taking your time: slow is smooth, smooth is fast.'),
    P('D — Developing routines: a flow for takeoff, level-off, climb.'),
    P('R — Raising awareness: know which situations raise the risk.'),

    S('Memory & Forgetting'),
    H('The Three Memory Systems — FI.I.B.K12'),
    A('Sensory memory'),
    P('Takes in everything through the five senses; discards what it deems unimportant.'),
    A('Short-term memory'),
    P('Holds information about 30 seconds — then it fades or transfers to long-term, depending on the value the learner puts on it.'),
    A('Long-term memory'),
    P('Effectively unlimited and relatively permanent. What transfers usually has emotional ties.'),
    B('Action: solidify important material by invoking positive emotion — stories, humor, memorable moments.', 3),
    P('Usage matters: information used frequently and recently is the easiest to retrieve.'),
    H('Forgetting — FIRRS — FI.I.B.K12b'),
    A('F — Fading'),
    P('Use it or lose it.'),
    A('I — Interference'),
    P('New, similar information overwrites the old — V-speeds across different airplanes.'),
    A('R — Retrieval failure'),
    P('Lost between short-term and long-term — never solidified.'),
    A('R — Repression'),
    P('Unconscious effort to forget — turbulence terror as a kid becomes an unexplained fear of turbulence as a student.'),
    A('S — Suppression'),
    P('CONSCIOUS effort to forget something upsetting or embarrassing.'),
    H('Retention of Learning — MALAMP — FI.I.B.K13'),
    P('"I can\'t learn without MALAMP":'),
    P('M — Meaningful repetition: 3–4 reps give maximum retention effect.'),
    P('A — Association: hook new knowledge to something known — descend, pull carb heat.'),
    P('L — Learning with all senses: the feeling in your seat during a steep turn teaches too.'),
    P('A — Attitude: learners must WANT to learn for it to stick.'),
    P('M — Mnemonics: acronyms, rhymes, phrases — this entire lesson is proof.'),
    P('P — Praise: responses that produce positive feelings get repeated.'),
    H('Transfer of Learning — FI.I.B.K14'),
    A('Positive transfer'),
    P('A past skill helps the new one — knows car engines, picks up aircraft engines fast.'),
    A('Negative transfer'),
    P('A past skill fights the new one — turning the yoke on the ground like a steering wheel.'),
    B('Action: anticipate negative transfer from driving, gaming, and other aircraft — and brief it before it bites.'),

    S('Conclusion'),
    P('Review: A MAP · RIC · G-STEP · MUA · REEPIR · CAP (RUAC/ARVOI/OIPH) · CTE · CAAR · DBR · SM · CULT DR · FIRRS · MALAMP · transfer.'),
    P('Every acronym here is a lever: readiness before the lesson, primacy during it, meaningful repetition after it.'),
  ]};

  /* ============================================================
     I.C — Course Development, Lesson Plans & Classroom Training
     Acronym spine: PPAR · SPAM · DCC · IDC (AMO) · FIT · ORDRR
     ============================================================ */
  window.CFI_SCRIPTS['i-c-course-development'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('Good instruction does not happen by accident, which is why we plan courses and lessons instead of winging it.'),
    H('Overview'),
    P('The teaching process (PPAR)'),
    P('Essential teaching skills (SPAM)'),
    P('Course of training, syllabus & lesson plans'),
    P('Objectives — performance vs decision-based (DCC)'),
    P('Lesson organization (IDC / AMO)'),
    P('Delivery methods — lecture (FIT), guided discussion (ORDRR), demo-performance'),
    P('E-learning & instructional aids'),
    P('Problem-based & integrated flight instruction'),
    H('What'),
    P('How to organize material and deliver it so a learner can actually absorb it.'),
    H('Why'),
    P('You can be a great pilot and a poor teacher. Structure is what turns knowledge into instruction.'),

    S('How:'),

    H('The Teaching Process — PPAR — FI.I.C.K1a'),
    P('Organizing material and teaching it so the student can understand:'),
    A('P — Preparation / Planning'),
    P('Syllabus, lesson plans, objectives, materials.'),
    A('P — Presentation'),
    P('Deliver the material by the method that fits the content and the learner.'),
    A('A — Application'),
    P('The learner performs — the skill or knowledge gets used.'),
    A('R — Review / Assessment'),
    P('Measure it against standards and feed it back.'),

    H('Essential Teaching Skills — SPAM — FI.I.C.K1b'),
    A('S — Subject Matter Expertise'),
    P('Know the aviation content cold — there is a lot of it.'),
    A('P — People Skills'),
    P('Understand the learner, satisfy their needs, communicate well.'),
    A('A — Assessment Skills'),
    P('Judge skill and development accurately and guide it (all of Task D).'),
    A('M — Management Skills'),
    P('Plan, lead, and organize every part of the learner\'s training — including time inside each flight lesson.'),
    P('Backseat orders the same four as "MAPS" — same skills, either order.', 3),

    S('Course Design & Planning'),
    H('Levels of Planning — FI.I.C.K2'),
    A('Course of Training'),
    P('The destination: the complete series of studies leading to the certificate or rating.'),
    A('Syllabus'),
    P('The route: a step-by-step, building-block sequence of lessons with review and assessment built in.'),
    A('Lesson Plan'),
    P('Today\'s leg: an organized outline for a single instructional period.'),
    A('Blocks of Learning'),
    P('Discrete skills that can each be taught, measured, and mastered — start broad, build the foundation, stack blocks on top.'),
    P('Master blocks individually; the syllabus arranges them in a logical sequence.', 3),

    H('Lesson Objectives — FI.I.C.K3'),
    A('Two types: Performance-Based and Decision-Based'),
    P('Performance-based: define exactly what is done and how — the early-training workhorse.'),
    P('Decision-based: designed to develop ADM and judgment — shift toward these as training progresses.'),
    A('Performance-Based Objectives — DCC'),
    P('D — Description of the skill: what behavior is being learned (a maximum-performance climbing turn — chandelle).'),
    P('C — Conditions: the rules for the demonstration (no more than 30° bank).'),
    P('C — Criteria: measurable standards — no question whether they passed (±10° on rollout).'),
    A('Importance of the ACS'),
    P('The ACS supplies the specific performance standards for certification.'),
    B('Action: use the ACS standards, but deliver them through scenarios rather than isolated maneuvers.', 3),

    S('Organizing & Delivering Lessons'),
    H('Organization of Material — IDC — FI.I.C.K4'),
    A('I — Introduction — AMO'),
    P('A — Attention: story, video, joke — earn the next 30 minutes.'),
    P('M — Motivation: why this matters to THEM.'),
    P('O — Overview: tell them what will be covered.'),
    A('D — Development'),
    P('The main body, organized in a way that makes sense:'),
    P('Past to present · Simple to complex · Known to unknown · Most frequently used to least.', 3),
    A('C — Conclusion'),
    P('Return to the important elements and tie them to the objective — "now that we understand left-turning tendencies, we can expect them and counteract with right rudder on takeoff."'),

    H('Training Delivery Methods — FI.I.C.K5'),
    A('Lecture — FIT'),
    P('Best for large groups, new information, and time management.'),
    P('F — Formal: inform or persuade with little participation — lots of info, little time.', 3),
    P('I — Illustrated talk: visual aids — gyro, pictures, the model airplane.', 3),
    P('T — Teaching lecture: delivered to allow learner participation.', 3),
    A('Discussion'),
    P('Short lecture, then discussion — the learner talks their way to understanding.'),
    A('Guided Discussion — ORDRR question types'),
    P('The goal is to DRAW OUT what the learners know rather than tell them:'),
    P('O — Overhead: to the whole group, the big question.', 3),
    P('R — Rhetorical: ask, pause, answer it yourself.', 3),
    P('D — Direct: aimed at one specific person.', 3),
    P('R — Reverse: they ask me, I answer with a question back.', 3),
    P('R — Relay: they ask me, I pass it to another learner.', 3),
    A('Cooperative / Group Learning'),
    P('Small groups organized to maximize learning from each other.'),
    A('Demonstration–Performance'),
    P('Explanation · Demonstration · Learner performance with supervision · Evaluation. The backbone of flight training.'),
    A('Drill and Practice'),
    P('Repetition builds retention and skill — connects straight to the Law of Exercise.'),

    H('E-Learning & Instructional Aids — FI.I.C.K6/K7'),
    A('E-Learning'),
    P('Self-paced learning (Sporty\'s, King, sims, role-playing, even games).'),
    P('Pros: time-flexible, cost-effective, easily updated. Cons: limited feedback, cannot ask questions.', 3),
    P('Aviation Training Devices: BATD · AATD · FTD · full flight simulators.', 3),
    A('Effective instructional aids'),
    P('Cover the key points, straightforward and factual, relatively simple.'),
    P('Reasons: assist the instructor, clarify relationships, help learners connect concepts.', 3),
    B('Action: establish the objective first, gather the data, organize the lesson plan — THEN pick which ideas need an aid.', 3),
    P('Types: whiteboard, print, syllabi/records/maneuvers guides, projected material, video, models and mock-ups.'),

    S('Advanced Instructional Methods'),
    H('Problem-Based Instruction & HOTS — FI.I.C.K9'),
    P('Lessons built on real-life situations with no single right answer — this is how you develop higher-order thinking (HOTS).'),
    P('Set up the problem · determine learning outcomes · solve it · reflect on the process · consider other solutions through guided discovery · re-evaluate.'),
    P('Scenario-Based Training is the PBL form we use most in flight training.', 3),
    H('Integrated Flight Instruction — FI.I.C.K8'),
    P('Every maneuver taught by BOTH outside visual references and instrument indications, from the first time it is introduced.'),
    P('Improves control, coordination, landings, and overall competency.'),
    B('90% outside, 10% inside — never let instrument focus kill see-and-avoid.'),
    B('Build judgment with PBL; build habits with integrated flight instruction.'),

    S('Conclusion'),
    P('Review: PPAR · SPAM · course/syllabus/lesson plan · DCC objectives · IDC (AMO intro) · FIT / ORDRR delivery · aids · PBL + IFI.'),
    P('A lesson plan is not paperwork — it is the difference between teaching and just talking.'),
  ]};

  /* ============================================================
     I.D — Student Evaluation, Assessment & Testing
     Acronym spine: FAST COCO · V CROUD · RRRR · WAC · CAB CAP ·
     TOP BIT
     ============================================================ */
  window.CFI_SCRIPTS['i-d-student-evaluation'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('Learners cannot fix what they do not know is broken, which is why we assess and give honest feedback on everything they do.'),
    H('Overview'),
    P('Characteristics of effective assessment (FAST COCO)'),
    P('Traditional assessment (V CROUD)'),
    P('Authentic assessment (RRRR · maneuver grades)'),
    P('Types of assessment (WAC)'),
    P('Critique — types & ground rules'),
    P('Oral questioning (CAB CAP · TOP BIT)'),
    P('Assessing piloting ability'),
    H('What'),
    P('How to measure a learner\'s progress and feed it back so it improves performance.'),
    H('Why'),
    P('Assessment highlights where they are lacking and excelling — it steers every lesson that follows.'),

    S('How:'),

    H('Characteristics of an Effective Assessment — FAST COCO — FI.I.D.K1'),
    P('F — Flexible: fit the learner and the occasion.'),
    P('A — Acceptable: the learner must accept YOU — your qualifications and sincerity — before they accept the critique.'),
    P('S — Specific: no doubt what was good, what was poor, and how to improve.'),
    P('T — Thoughtful: never ridicule or anger — respect their need for self-esteem and approval.'),
    P('C — Comprehensive: strengths AND weaknesses.'),
    P('O — Objective: standards-based, not your opinions or preferences — the ACS is an objective yardstick.'),
    P('C — Constructive: the learner must benefit; it corrects the deficient areas.'),
    P('O — Organized: logical pattern, or it loses its impact.'),

    H('Traditional Assessment — V CROUD — FI.I.D.K2'),
    P('Written tests: multiple choice, matching, true/false. A good grade may not reflect ability. A good test has:'),
    P('V — Validity: measures the lesson objectives and nothing else.'),
    P('C — Comprehensiveness: samples a good cross-section of the knowledge.'),
    P('R — Reliability: yields consistent results.'),
    P('O — Objectivity: can be graded consistently.'),
    P('U — Usability: easy to give, read, and grade.'),
    P('D — Discrimination: separates those who know the material from those who do not.'),

    H('Authentic Assessment — FI.I.D.K3'),
    P('The learner performs REAL-WORLD tasks and demonstrates meaningful application — no multiple choice. The checkride is one.'),
    A('Learner-Centered Assessment — RRRR (4 open-ended steps)'),
    P('R — Replay: the student verbally replays the lesson — gives the steps of the maneuver.'),
    P('R — Reconstruct: identifies what they could have done differently.'),
    P('R — Reflect: places meaning on the experience — insight comes from here.'),
    P('R — Redirect: relates the lesson to other experiences and future lessons.'),
    A('Maneuver / Procedure Grades'),
    P('Describe · Explain · Practice · Perform.'),
    P('Describe: knows the elements, needs help executing. Explain: understands concepts, still needs help. Practice: plans and executes, assistance corrects deviations. Perform: identifies and corrects their own errors — no instructor needed.', 3),
    A('Assessing Risk Management Skills'),
    P('Explain · Practice · Manage/Decide.'),
    P('Manage/Decide = gathers the important data, identifies courses of action, evaluates the risk in each, and makes the appropriate decision — without help.', 3),

    H('Choosing & Structuring Assessment — FI.I.D.K4'),
    P('Determine level-of-learning objectives · list indicators of desired behavior · establish criterion-based objectives · develop criterion-referenced items.'),
    A('Types of Assessments — WAC'),
    P('W — Written: MC, matching, true/false.'),
    P('A — Authentic: real-world tasks (checkrides).'),
    P('C — Collaborative: open-ended questions using HOTS — improves ADM.'),

    S('The Art of Critique'),
    H('Critique — FI.I.D.K5'),
    P('Instructor-to-learner feedback paired with an assessment — covers good AND bad, the parts and the whole.'),
    A('Six types of critique'),
    P('Instructor/learner critique · Learner-led · Small group · Critique by another learner (correct it if it\'s wrong) · Self-critique · Written (gives the learner a copy to keep).'),
    A('Ground rules'),
    P('Stay inside the scheduled time. Cover at most 4–5 correction points. Leave time for a summary. Avoid absolute statements, avoid controversies and taking sides, never get maneuvered into defending a criticism. Written must match oral.'),
    B('Goal: the learner leaves knowing exactly what to improve — and confident they can.'),

    H('Oral Assessment & Questioning — FI.I.D.K6'),
    P('Direct questioning — the most common assessment there is. Reveals effectiveness, checks retention, keeps heads in the game, and identifies what needs re-emphasis.'),
    A('Effective questions — CAB CAP'),
    P('C — Clear and definite · A — Apply to the lesson (relevant) · B — Brief and concise · C — Center on one idea · A — Adapted to the student\'s experience · P — Present a challenge.'),
    A('Questions to avoid — TOP BIT'),
    P('T — Toss-up (two viable options, yes/no) · O — Oversize (too broad) · P — Puzzling (too many parts) · B — Bewildering (hard to even read) · I — Irrelevant · T — Trick questions.'),
    A('Answering learner questions'),
    P('Understand the question · give a direct answer · verify they are satisfied.'),
    B('Action: if you do not know — "great question, let me find out and get back to you." Never bluff.', 3),

    S('Assessing Piloting Ability'),
    H('In Flight and After — FI.I.D.K7'),
    A('During flight'),
    P('Assess against the established standards for THAT learner\'s stage.'),
    B('Action: when it is safe, let the mistake develop and assess their correction — that is where the learning is.', 3),
    A('Postflight evaluation'),
    P('Keep the learner informed of progress every single lesson; with SBT, use collaborative assessment when a scenario completes.'),
    A('Solo flight'),
    P('Positive, confidence-building experience. Instructor present and available, portable radio if possible, comms to a minimum — never talk on short final. Debrief right after and reinforce correct procedures.'),
    A('Practical test recommendations'),
    B('A serious instructor responsibility: your signature says this pilot is safe and competent — they resemble you and your training.'),

    S('Conclusion'),
    P('Review: FAST COCO · V CROUD · authentic (RRRR, Describe/Explain/Practice/Perform) · WAC · critique types and ground rules · CAB CAP vs TOP BIT · assessing ability through solo and recommendation.'),
    P('Assessment is not the report card at the end — it is the steering wheel of the whole course.'),
  ]};

  /* ============================================================
     I.E — Effective Teaching in a Professional Environment
     Acronym spine: MACKBAG · SAD PP
     ============================================================ */
  window.CFI_SCRIPTS['i-e-effective-teaching-pro-env'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('Your students will fly the way you taught them long after you are gone, which is why professionalism is not optional.'),
    H('Overview'),
    P('Aviation instructor responsibilities (MACKBAG)'),
    P('Flight instructor responsibilities'),
    P('Qualifications & professionalism (SAD PP)'),
    P('Professional development'),
    P('Ethics & conduct (FIMCC)'),
    H('What'),
    P('What the FAA — and your learners — expect from you as a professional educator.'),
    H('Why'),
    P('You lay the foundation for someone\'s entire aviation career. Professionalism is not optional equipment.'),

    S('How:'),

    H('Aviation Instructor Responsibilities — FI.I.E.K1'),
    A('Helping learners learn'),
    P('Learning should be interesting AND enjoyable — make it beneficial and fun; measure against standards.'),
    A('Providing adequate instruction'),
    P('Analyze each learner\'s personality, thinking, and ability, then tailor.'),
    P('Slow progress: assign easier sub-goals to rebuild momentum. Fast progress: watch for the belief that error-correction no longer matters. Complex tasks: break into elements, practice each, then recombine.', 3),
    A('Training to established standards'),
    B('Letting substandard performance slide fails the student — strive for excellence, hold the line.'),
    A('Emphasizing the positive'),
    P('Positive instruction results in positive learning — make the first lessons enjoyable; they set the tone (Law of Primacy).'),
    A('Ensuring aviation safety'),
    P('Teach safety habits, risk management, and decision-making from day one — students copy what they see you do.'),
    A('Minimizing learner frustration — MACKBAG'),
    P('M — Motivate students.'),
    P('A — Approach learners as individuals — every personality is different.'),
    P('C — Constructive criticism, never ridicule.'),
    P('K — Keep learners informed of their progress.'),
    P('B — Be consistent — same checklists, same standards, every time.'),
    P('A — Admit when you are wrong; we all make mistakes.'),
    P('G — Give credit when due — praise, but do not water it down by overusing it.'),

    H('Flight Instructor Responsibilities — FI.I.E.K2'),
    P('Mold a safe pilot with a professional approach to aviation.'),
    A('Ensuring learner skill set'),
    P('You decide when they are ready to solo — they must consistently prove the maneuvers on their own.'),
    A('Physiological obstacles for flight learners'),
    P('Strange noises, G-forces, motion sickness, fear of small airplanes — never ignore or ridicule; most are overcome once the learner understands the cause.'),
    A('Endorsements & recommendations'),
    P('Knowledge tests, practical test recommendations, retesting after failure, solo endorsements — each one is your name on their readiness.'),
    A('See and avoid'),
    B('Action: your eyes stay OUTSIDE while the student performs the maneuver.'),
    A('Currency vs. proficiency'),
    P('Currency = the FAA bare minimums. Proficiency = recent enough practice to be genuinely safe and competent. Teach learners to chase proficiency.'),
    A('Supervision & surveillance'),
    P('Supervise solos and cross-countries, and supervise the overall progress of training.'),

    H('Qualifications & Professionalism — SAD PP — FI.I.E.K3'),
    P('Stay thoroughly familiar with every instrument, avionics unit, and system you teach in; stay current on certification requirements.'),
    A('S — Sincerity'),
    P('Straightforward and honest, always.'),
    A('A — Acceptance of the learner'),
    P('Accept them as they are — acceptance rather than ridicule.'),
    A('D — Demeanor'),
    P('Your attitude and behavior build (or wreck) the professional image — the vibe you radiate is part of the instruction.'),
    A('P — Personal appearance and habits'),
    P('Neat, clean, dressed to be taken seriously. Hygiene matters in a small cockpit.'),
    A('P — Proper language'),
    P('Speak positively and descriptively; keep the profanity out of the cockpit.'),

    H('Professional Development — FI.I.E.K4'),
    P('Do not go complacent — keep improving your qualifications and freshening your material.'),
    P('Continuing education: seminars, workshops, the WINGS program.'),
    P('Reflective teaching: keep asking what YOU could have taught better.'),
    P('Maintain a library of current procedures and publications.'),
    P('Additional ratings — and the Gold Seal Flight Instructor Certificate.'),

    H('Instructor Ethics & Conduct — FI.I.E.K5'),
    P('The Flight Instructor\'s Model Code of Conduct (FIMCC):'),
    P('Make safety the number one priority · Develop and exercise good judgment · Recognize and manage risk · Be accountable for your actions · Act with responsibility and courtesy · Adhere to prudent operating practices · Adhere to applicable laws and regulations.'),

    S('Conclusion'),
    P('Review: responsibilities (MACKBAG for frustration) · flight-instructor duties (skill set, endorsements, see-and-avoid, currency vs proficiency) · SAD PP professionalism · development · FIMCC ethics.'),
    P('The through-line: your students become the kind of pilot you model, not the kind you describe.'),
  ]};

  /* ============================================================
     I.F — Effective Teaching: Risk Management & Accident Prevention
     Acronym spine: PAVE · TEAM · 5 P's · FRAT · DECIDE · MIRIA
     ============================================================ */
  window.CFI_SCRIPTS['i-f-effective-teaching-rm'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('Flying is inherently dangerous, which is why we as pilots manage the risk effectively so that we can enjoy it without having things go wrong.'),
    H('Overview'),
    P('Risk management principles & the 3-step process'),
    P('Tools — PAVE · TEAM · 5 P\'s · FRAT'),
    P('Teaching RM by phase of training'),
    P('Managing risk during flight instruction'),
    P('ADM — DECIDE, hazardous attitudes (MIRIA), SRM/CRM'),
    H('What'),
    P('How to identify, assess, and mitigate risk — and how to teach learners to do it instinctively.'),
    H('Why'),
    B('Teaching learners to recognize and mitigate risk is the single most safety-critical thing an instructor does.'),

    S('How:'),

    H('Principles of Risk Management — FI.I.F.K1'),
    P('Accept no unnecessary risk · Make risk decisions at the appropriate level · Accept risk only when benefits outweigh costs · Integrate RM into planning at ALL levels.'),

    H('The 3-Step Risk Management Process'),
    A('1 — Identify the hazard (PAVE)'),
    P('A hazard is any real or potential condition that can cause injury, illness, death, or damage — find them with the PAVE checklist.'),
    A('2 — Assess the risk'),
    P('How LIKELY is the loss, and how SEVERE would it be? Plot it on the risk assessment matrix (likelihood × severity).'),
    A('3 — Mitigate the risk (TEAM)'),
    P('T — Transfer it · E — Eliminate it · A — Accept it (when benefits outweigh) · M — Mitigate what remains.'),
    P('Cancel, reroute, delay — or for the Denver scenario: bring an experienced CFI and get checked out in the airspace.', 3),

    H('Risk Management Tools — PAVE — FI.I.F.K2'),
    A('P — Pilot'),
    P('Am I personally ready for this flight? Run IMSAFE: Illness, Medication, Stress, Alcohol, Fatigue, Emotion.'),
    A('A — Aircraft'),
    P('Is this aircraft suitable? Airworthy (ARROW documents), equipped for the mission (IFR?), maintenance current.'),
    A('V — enVironment'),
    P('Weather, terrain, airports — brief it with NWKRAFT: NOTAMs, Weather, Known ATC delays, Runway lengths, Alternates, Fuel, Takeoff/landing distances.'),
    A('E — External pressures'),
    B('The killer: would I still go if this pressure did not exist? If no — do not go. Get-there-itis has no place in a training airplane.'),
    A('The 5 P\'s — in-flight decision points'),
    P('Plan (weather, route, fuel — it keeps changing; adjust with it) · Plane (condition, equipment, automation) · Pilot (IMSAFE again, in flight) · Passengers (their wants pressure your decisions — you are PIC) · Programming (set up avionics ahead of time; know when NOT to be heads-down).'),
    A('Flight Risk Assessment Tool (FRAT)'),
    P('A scored questionnaire that turns risk into a number and a go/no-go picture.'),
    P('Roughly: ≤10 low risk · 11–20 exercise caution · 21–30 area of concern.', 3),

    S('Teaching & Managing Risk'),
    H('Teaching Risk Management — FI.I.F.K3/K4'),
    B('Introduce RM at the very beginning of training — it is a practice woven into every flight, never a separate subject.'),
    B('Action: learners need to SEE you practicing RM — model it, then hand them the lead.'),
    A('Techniques by phase of instruction'),
    P('Pre-solo: RM discussion in preflight and postflight briefings; FRAT before each solo.'),
    P('Post-solo / pre-XC: learner performs some of the assessment; FRAT plus discussion.'),
    P('Cross-country: learner runs the full risk analysis before every flight and reviews it with you.'),
    P('Instrument: weather and avionics familiarity dominate — hard IMC in a six-pack is not hard IMC in a G1000.'),
    P('Flight review / recurrency: it has probably been a while — build scenarios that fit the pilot they actually are; no hard-IMC scenarios for a crop duster.'),
    H('Managing Risk During Flight Instruction — FI.I.F.K5'),
    P('Same tools, applied to the instructional flight itself — run PAVE with the learner involved in every step.'),
    P('Pilot: qualification and IMSAFE risks — for BOTH of you. Aircraft: maintenance, right plane for the job. enVironment: collision hazards, terrain, busy airspace. External: squeezing flights into busy schedules and weather windows.', 3),
    A('Takeoff & landing special considerations — low and slow'),
    B('Action: set a limit of error — how far you let the learner deviate before you intervene. It gives them room to fix their own mistakes and you time to recover.'),
    P('Do not practice near YOUR personal minimums. Teach before calling tower, not during high-focus moments. Anticipate the likely landing errors before they happen — crosswinds, low approach speeds.'),

    S('ADM & Human Factors'),
    H('Aeronautical Decision Making — FI.I.F.K6'),
    P('A systematic approach to consistently determine the best course of action for the circumstances.'),
    A('The DECIDE model'),
    P('D — Detect a problem (make sure it IS one) · E — Estimate the need to react · C — Choose a desirable outcome · I — Identify solutions · D — Do the action · E — Evaluate its success.'),
    H('Obstacles to Situational Awareness — FI.I.F.R2'),
    P('Distractions: a big factor in accidents — always fly the airplane first.'),
    P('Fatigue: less alert, worse performance — the only real remedy is sleep.'),
    P('Complacency: overconfident and hard to recognize.'),
    B('Action: probe complacency — ask for the position of other traffic in the pattern, or hand them a made-up problem and watch their SA.', 3),
    H('Hazardous Attitudes & Antidotes — MIRIA — FI.I.F.R3'),
    A('M — Macho: "watch this"'),
    P('Antidote: taking chances when flying is foolish.'),
    A('I — Impulsivity: reacting without thinking'),
    P('Antidote: not so fast — think first.'),
    A('R — Resignation: "what\'s the use, I give up"'),
    P('Antidote: I am not helpless; I can make a difference.'),
    A('I — Invulnerability: "that happens to other people"'),
    P('Antidote: it could happen to me.'),
    A('A — Anti-authority: "don\'t tell me what to do"'),
    P('Antidote: follow the rules — they are usually right.'),
    B('Recognize the thought, name it, apply the antidote — teach learners to do this out loud at first.'),
    H('Stress & Resource Management'),
    P('Good stress: moderate, keeps the learner on high alert, improves skill — dose it to their level and push limits slightly.'),
    P('Bad stress: beyond their skill level — skills deteriorate fast.'),
    A('SRM / CRM'),
    P('How to gather information, analyze it, and decide — CRM adds the team: dispatchers, other pilots, cabin, maintenance, ATC.'),
    P('Use of resources: every available one — weather sources, ATC, performance sheets, equipment.', 3),
    P('Workload management: plan, prioritize, and sequence to stay ahead; prepare for high-workload phases BEFORE they arrive; recognize the pile-up (busy airspace, strong tailwind, tasks stacking).', 3),

    S('Conclusion'),
    P('Review: principles · Identify (PAVE) / Assess (matrix) / Mitigate (TEAM) · 5 P\'s and FRAT · teach RM from day one and by phase · limit-of-error while instructing · DECIDE, SA obstacles, MIRIA antidotes, SRM/CRM.'),
    P('The instructor\'s job: teach, practice, model, and coach risk management until the learner does it without being asked.'),
  ]};

  /* ============================================================
     II.A — Human Factors
     Spine: the 4 H's of hypoxia · IMSAFE · COLD · 8-hour rule
     ============================================================ */
  window.CFI_SCRIPTS['ii-a-human-factors'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('The human body was not built for flight, which is why we as pilots need to know how it fails up there — and what to do when it does.'),
    H('Overview'),
    P('Hypoxia (4 types) & hyperventilation'),
    P('Ears, sinuses & spatial disorientation'),
    P('Motion sickness & carbon monoxide'),
    P('Fatigue, stress, dehydration & hypothermia (COLD)'),
    P('Landing illusions'),
    P('Scuba, alcohol & drugs (8-hour rule)'),
    P('IMSAFE & managing aeromedical risk'),
    H('What'),
    P('The aeromedical factors that degrade a pilot — how to recognize them, treat them, and keep them out of the cockpit.'),
    H('Why'),
    P('Most of these hit judgment first — the part of you that would notice is the part that fails.'),

    S('How:'),

    H('Hypoxia — AI.II.A.K1a'),
    P('"Not enough oxygen." Four types — the four H\'s:'),
    A('Hypoxic Hypoxia'),
    P('Not enough oxygen available to the lungs.'),
    P('The pilot version: reduced partial pressure of oxygen at altitude — the classic high-altitude hypoxia.', 3),
    A('Hypemic Hypoxia'),
    P('The blood cannot pick up and carry enough oxygen — low blood volume, blood disease, or hemoglobin that is occupied.'),
    P('CO poisoning is hypemic: carbon monoxide takes hemoglobin\'s seat and oxygen cannot ride.', 3),
    A('Stagnant Hypoxia'),
    P('Oxygen-rich blood is not MOVING to the tissues — your arm "falling asleep."'),
    P('In flight: G-forces, shock, a constricted artery, or a failing heart.', 3),
    A('Histotoxic Hypoxia'),
    P('"Histo" = tissue, "toxic" = poison. Oxygen arrives at the cells but they cannot use it.'),
    P('Causes: alcohol, narcotics, poisons — one drink at altitude works on you like several.', 3),
    A('Symptoms of hypoxia'),
    P('Cyanosis (blue lips and fingernails), headache, delayed reactions, impaired judgment, euphoria, visual impairment, drowsiness, dizziness, tingling, numbness.'),
    B('Euphoria is the trap — you feel GOOD while dying. That is why hypoxia kills pilots who "felt fine."'),
    A('Time of Useful Consciousness'),
    P('The maximum time to make and carry out rational decisions without supplemental oxygen — shrinks fast with altitude.'),
    A('Treatment'),
    P('Lower altitude and supplemental oxygen. The FAA offers a one-day physiology course with an altitude chamber to feel YOUR symptoms safely.'),

    H('Hyperventilation — AI.II.A.K1b'),
    P('Emotional stress, fright, or pain drives breathing rate and depth up — you blow off too much CO2.'),
    P('Symptoms mimic hypoxia: visual impairment, dizziness, tingling, hot/cold sensations, muscle spasms, even unconsciousness.'),
    A('Treatment'),
    P('Breathe normally — talk out loud, or breathe into a paper bag.'),
    B('If you cannot tell which one it is, treat for hypoxia — it is the one that kills faster.'),

    H('Middle Ear & Sinus Problems — AI.II.A.K1c'),
    P('The eustachian tube equalizes middle-ear pressure with the cabin; congestion blocks it, and descent traps a vacuum behind the eardrum — pain and hearing loss.'),
    P('Relief: swallow, yawn, chew, or valsalva. Slow the descent if a passenger cannot clear.'),
    B('A cold, sinus infection, or allergies can make equalizing impossible — that is a no-go, and decongestants have their own side effects.'),

    H('Spatial Disorientation — AI.II.A.K1d'),
    P('Losing track of the airplane\'s position, attitude, or movement in space.'),
    A('The body orients with 3 systems'),
    P('Visual — the eyes, by far the largest source of information.'),
    P('Vestibular system (inner ear) — motion sensing; fluid in the semicircular canals.'),
    P('Somatosensory system (nerves) — "seat of the pants" position sense from gravity, feeling, and sound.'),
    A('Spatial disorientation & flight'),
    P('Flight feeds the three systems CONFLICTING information — the inner ear stops sensing a steady turn, the seat of the pants is fooled by G-load.'),
    B('Countering it: recognize the problem, disregard the false sensations, and trust the flight instruments. The full illusion list lives in II.B.'),

    H('Motion Sickness — AI.II.A.K1e'),
    P('The brain receiving conflicting messages about the body\'s state — anxiety and stress feed it.'),
    P('Symptoms: general discomfort, nausea, dizziness, paleness, sweating, vomiting.'),
    A('Treatment'),
    P('Open the fresh-air vents, focus outside the airplane, minimize head movement — and hand them the controls: flying smooth, straight and level cures most students.'),

    H('Carbon Monoxide Poisoning — AI.II.A.K1f'),
    P('CO is a colorless, odorless product of combustion; an exhaust leak puts it in the cabin — usually through the heater.'),
    P('In the body it binds hemoglobin and blocks oxygen transport — hypemic hypoxia, headache, blurred vision, dizziness, loss of muscle power.'),
    A('Detecting & correcting'),
    P('CO detector on the panel; if you smell exhaust, assume CO is present.'),
    B('If suspected: heater off, vents and windows open, land as soon as possible, 100% oxygen if available.'),

    S('Fatigue, Stress & the Body'),
    H('Fatigue — AI.II.A.K1h'),
    P('One of the most treacherous hazards to flight safety — it degrades judgment and decision-making before you notice.'),
    P('Acute (short-term): normal everyday tiredness — rest fixes it.'),
    P('Chronic: builds when recovery never happens — physiological and psychological roots (money, home, work).'),
    B('Chronic fatigue = do not fly. The only real remedy for fatigue is sleep.'),
    H('Stress — AI.II.A.K1g'),
    P('The body\'s response to the demands placed on it — stressors stack: physical, physiological, psychological.'),
    P('Acute stress: immediate demand, fight-or-flight. Chronic stress: unrelenting load that exceeds the ability to cope.'),
    B('Stress is cumulative — the fight at home rides along on the checkride.'),
    H('Dehydration & Nutrition — AI.II.A.K1i'),
    P('Critical water loss: hot flight decks, wind, humidity, and diuretics (coffee, tea, alcohol) all pull water out.'),
    P('Effects: fatigue, poor concentration, headaches, cramps, sleepiness. Prevention is simply water — carry it.'),
    P('Nutrition: skipped meals mean low blood sugar, distraction, and a breakdown in performance — eat regular, sized meals.'),
    H('Hypothermia — AI.II.A.K1j'),
    P('The body loses heat faster than it produces it (below ~95°F core). Heat leaves by radiation, direct contact, and wind.'),
    P('Symptoms: shivering, slurred speech, slow shallow breathing, weak pulse, clumsiness.'),
    A('Prevention — COLD'),
    P('C — Cover: protective clothing. O — Overexertion: avoid sweating. L — Layers: loose, lightweight layers. D — Dry: get out of wet clothes immediately.'),

    S('Illusions & Substances'),
    H('Landing / Optical Illusions — AI.II.A.K1k'),
    A('Runway width'),
    P('Narrow runway · you feel high · you fly a LOW approach. Wide runway · the opposite.'),
    A('Runway & terrain slope'),
    P('Upslope · you feel high · low approach. Downslope · the opposite.'),
    A('Featureless terrain'),
    P('Water or darkness with no ground features · you feel high · low approach ("black-hole approach").'),
    A('Atmospheric'),
    P('Rain on the windscreen · feel high. Haze · feel farther away. Fog penetration · an illusion of pitching up, so pilots steepen the approach.'),
    A('Ground lighting'),
    P('A straight road or train at night imitates a runway; brilliant runway lighting feels closer than it is · high approach.'),
    B('Prevention: anticipate them on every approach and back yourself up with the glide slope or VASI/PAPI.'),
    H('Nitrogen & Scuba Diving — AI.II.A.K1l'),
    P('Diving loads the blood with dissolved nitrogen; climbing too soon brings it out of solution — decompression sickness, severe pain, worst-case death.'),
    B('Wait times: 12 hours after any dive before flying to 8,000 ft; 24 hours if the dive required controlled ascent or you will fly above 8,000.'),
    H('Alcohol & Other Drugs — AI.II.A.K2/K3'),
    P('Alcohol blocks the brain\'s ability to use oxygen (histotoxic), and altitude multiplies its effect.'),
    B('FAR 91.17: 8 hours bottle-to-throttle, under 0.04, AND not feeling any effects — whichever is longest.'),
    P('FAR 61.53: do not fly with any medical condition or medication that would prevent holding your medical; no medication without knowing its effects — when in doubt, FAA-approved or grounded.'),

    S('ADM & Managing Aeromedical Risk'),
    H('IMSAFE — the personal preflight — AI.II.A.R3'),
    P('I — Illness · M — Medication · S — Stress · A — Alcohol · F — Fatigue · E — Emotion.'),
    B('Action: run it out loud with the learner before every flight until they run it without you.'),
    H('RM: Combat expectation bias — AI.II.A.R4'),
    P('You see and hear what you EXPECT — the readback you expected is not always the clearance you got.'),
    H('RM: Hazardous attitudes — AI.II.A.R2'),
    P('Attitude drives decision quality — spot MIRIA (macho, impulsivity, resignation, invulnerability, anti-authority) and apply the antidote. Full treatment in I.F.'),
    H('Recognize when stress is affecting a learner'),
    P('Performance drops, irritability, tunnel vision — have them self-assess, set realistic goals, and delay training if necessary.'),
    H('Use all resources'),
    P('Internal: your knowledge, checklists, equipment. External: ATC, flight following, other pilots.'),
    P('Workload management: plan, prioritize, sequence — stay ahead of high-workload phases.'),

    S('Conclusion'),
    P('Review: four H\'s of hypoxia · hyperventilation · ears · spatial disorientation · motion sickness · CO · fatigue/stress/dehydration · COLD · landing illusions · scuba and the 8-hour rule · IMSAFE.'),
    P('The pattern: almost every one of these is caught on the ground by an honest IMSAFE — that is the lesson.'),
  ]};

  /* ============================================================
     II.B — Visual Scanning & Collision Avoidance
     Spine: see-and-avoid · scanning technique · ICEFLAGS illusions
     ============================================================ */
  window.CFI_SCRIPTS['ii-b-scanning-collision-avoidance'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('Most midair collisions happen in clear weather, in daylight, within a few miles of an airport — which is why we as pilots scan like our lives depend on it, because they do.'),
    H('Overview'),
    P('See and avoid (FAR 91.113)'),
    P('Proper visual scanning technique'),
    P('Collision risks & clearing procedures'),
    P('Recognizing a collision course'),
    P('Tools — lights, ADS-B, flight following, safety pilot'),
    P('Conditions that degrade vision'),
    P('Vestibular & visual illusions (ICEFLAGS)'),
    H('What'),
    P('How the eyes actually work in flight, how to scan effectively, and how to avoid hitting anyone.'),
    H('Why'),
    P('See-and-avoid is a regulatory duty — vigilance at all times, and the pilot is ALWAYS responsible for traffic, radar services or not.'),

    S('How:'),

    H('See and Avoid — FAR 91.113 / AC 90-48 — AI.II.B.K3'),
    P('Vigilance shall be maintained at all times by each person operating an aircraft.'),
    B('Often a shared job — never a delegated one. ADS-B and ATC help; the responsibility stays in your seat.'),

    H('Proper Visual Scanning — AIM 8-1-6 — AI.II.B.K4'),
    A('Fovea vs. peripheral vision'),
    P('Fovea (center of vision): the only part that sends a sharp image — a tiny cone of clarity.'),
    P('Peripheral: blurry, but excellent at detecting MOTION — your collision-threat detector.'),
    A('Effective scanning'),
    P('Short, regularly spaced eye movements — about 10° per second — bringing successive blocks of sky into the fovea.'),
    P('Day: scan with the center of vision. Night: use off-center/peripheral viewing — the fovea is nearly blind in the dark.', 3),
    B('90% outside, 10% inside. Poor scanning is the single biggest contributor to midair risk — remove the distractions.'),

    H('Collision Risks & Clearing Procedures — AI.II.B.K5/K7'),
    A('RM: High-traffic areas'),
    P('Class B/C/D and E surface areas, VORs, VFR waypoints and corridors, training areas, and airways — expect company there.'),
    A('Clearing procedures'),
    P('Before takeoff: scan the approach and departure paths.'),
    P('Climbs & descents: gentle banks left and right to clear the nose.'),
    P('Straight & level: clearing procedures at periodic intervals.'),
    P('Traffic patterns: never enter the pattern while descending.'),
    P('Training: clearing turns before EVERY maneuver.'),
    P('Blind spots: lift or lower the wing before turning — high-wing and low-wing hide different sky.'),

    H('Recognizing a Collision Course — AI.II.B.K6'),
    B('12.5 seconds: the minimum time to spot traffic, identify it, recognize the threat, and react.'),
    A('Determining relative altitude'),
    P('Above the horizon = probably above you; below the horizon = probably below you.'),
    B('An aircraft with NO relative motion — just growing — is on a collision course with you.'),
    P('If it is: act immediately. Safety first, but know the right-of-way rules (FAR 91.113) cold.'),

    H('Collision Avoidance Tools — AIM 8-1-8'),
    P('Flight deck management: organize before you fly so your head stays up.'),
    P('Keep windscreens clean, do not block windows, adjust for blind spots.'),
    P('Be visible: exterior lights on, interior lights low at night.'),
    P('ADS-B traffic on the display with alerts — a supplement, never a substitute.'),
    P('Flight following for radar advisories whenever possible.'),
    P('RM: a safety pilot is another set of eyes — use one for hood work, always.'),

    H('Conditions that Degrade Vision — AI.II.B.K1'),
    P('Physical: drugs and medication, exhaustion, poor diet, alcohol, smoking, CO, and lack of oxygen — night vision goes first.'),
    P('Environmental: dim light, glare, smoke, haze, dust.'),
    P('Dark adaptation takes 30 minutes — and one flash of white light to destroy.'),
    P('RM: empty-field myopia — with nothing to focus on, the eyes relax to a short focal distance and miss distant traffic; focus on ground features or the wingtip periodically.'),

    H('Vestibular & Visual Illusions — ICEFLAGS — AI.II.B.K2'),
    P('The inner-ear illusions from II.A, cataloged — remember ICEFLAGS:'),
    A('I — Inversion'),
    P('Abrupt level-off from a climb · feels like tumbling backward · pilot shoves the nose down.'),
    A('C — Coriolis'),
    P('Abrupt head movement during a prolonged turn · sensation of rotating on a different axis · dangerous attitude chasing a phantom.'),
    B('The head-down-to-grab-a-pen illusion — brief your passengers and keep your head still in IMC.', 3),
    A('E — Elevator'),
    P('An updraft\'s vertical acceleration feels like a climb · pilot pushes over (downdraft = the reverse).'),
    A('F — False Horizon'),
    P('Sloping cloud decks, obscured horizons, or lines of lights get mistaken for level — the pilot aligns with the wrong "horizon."'),
    A('L — The Leans'),
    P('A bank entered too slowly to feel, then corrected abruptly · feels like banking the OTHER way · pilot rolls back into the original turn.'),
    A('A — Autokinesis'),
    P('Stare at a single static light in the dark and it appears to move — chase it and lose control.'),
    A('G — Graveyard Spin & Spiral'),
    P('Spin recovery stops stimulating the inner ear · feels like spinning the other way · pilot re-enters the original spin.'),
    P('Spiral: a prolonged turn feels like wings-level descent · pilot pulls, tightening the spiral and loading the wings.', 3),
    A('S — Somatogravic'),
    P('Rapid acceleration feels like pitching up · pilot pushes into a dive (deceleration = the nose-up/stall version).'),
    B('Prevention for all of them: reference the flight instruments and believe them over your body.'),

    S('Conclusion'),
    P('Review: see-and-avoid duty · fovea vs peripheral, 10°-per-second blocks · clearing procedures · 12.5 seconds and no-relative-motion · lights, ADS-B, flight following, safety pilot · vision killers · ICEFLAGS.'),
    P('Teach it as habit, not knowledge: eyes outside, clearing turns every maneuver, instruments over inner ear.'),
  ]};

  /* ============================================================
     II.C — Runway Incursion Avoidance
     Spine: prevent · plan/brief/review · signs & markings · hold short
     ============================================================ */
  window.CFI_SCRIPTS['ii-c-runway-incursion-avoidance'] = { nodes: [
    S('Introduction'),
    H('Attention'),
    P('About three runway incursions happen every single day in the US, which is why we as pilots treat every hold-short line like the edge of an active runway — because it is.'),
    H('Overview'),
    P('What a runway incursion is & why they happen'),
    P('Taxi instructions, clearances & readbacks'),
    P('Plan, brief, review'),
    P('Sterile flight deck & task prioritization'),
    P('Airport markings, signs & lights'),
    P('Hold lines, night, low visibility & lost SA'),
    H('What'),
    P('How to move an airplane on the ground without ever ending up on a runway you were not cleared onto.'),
    H('Why'),
    P('Roughly 65% of incursions are caused by pilots — and about half of those are GA. This is our problem to fix.'),

    S('How:'),

    H('Runway Incursions — AI.II.C.K1'),
    P('Any occurrence at an airport involving an aircraft, vehicle, person, or object on the ground that creates a collision hazard with an aircraft taking off, landing, or intending to.'),
    A('Causal factors'),
    P('Failure to comply with ATC instructions, lack of airport familiarity, and nonconformance with SOPs.'),
    P('The taxi environment is genuinely hard: complex layouts, traffic, checklists, radios, passengers — all competing for attention.', 3),
    A('Preventive practices'),
    P('Maintain SA on your position AND other aircraft. Review the airport diagram and signage. Check NOTAMs. Use proper phraseology.'),
    P('Write down complex taxi instructions. Read back all hold-short and crossing instructions. Request progressive taxi when unsure.'),
    P('Lights and beacon on while taxiing. Check for traffic before crossing ANY hold line. After landing, clear the runway fully, then stop for taxi instructions.'),

    H('Taxi Instructions & Clearances — AI.II.C.K2'),
    P('Approval required before moving on the movement area; explicit clearance required before crossing any runway.'),
    P('ATC will give: where to taxi to, the route, and hold-short or crossing instructions for any runway on the way.'),
    A('Always read back'),
    B('The runway assignment · any clearance to ENTER a specific runway · any instruction to HOLD SHORT of a specific runway.'),
    A('Uncontrolled fields — AI.II.C.K6'),
    P('Announce intentions on CTAF, keep the taxi diagram out, monitor and build the picture, and apply right-of-way with generosity.'),

    H('Plan, Brief, Review'),
    P('Plan: current airport diagram in hand, expected routes reviewed, closed taxiways checked, standard taxi routes noted.'),
    P('Brief: the taxi route, the hot spots, and what you expect from everyone in the airplane (AC 91-73).'),
    P('Review: write ATC\'s instructions down, then review the route — query ATC the moment anything is confusing.'),

    H('RM: Sterile Flight Deck & Task Prioritization — AI.II.C.K5/R1'),
    B('Taxiing comes first. All heads-down work happens only when the aircraft is STOPPED.'),
    P('Near other aircraft: eyes outside, taxi slowly, run a continuous loop updating where everyone is.'),
    P('Be extra vigilant when a similar call sign is on frequency.'),

    S('Airport Markings, Signs & Lights — AI.II.C.K4'),
    H('Taxiway Markings'),
    A('Taxiway centerline markings'),
    P('Single continuous yellow line — the wingtip-clearance guarantee lives on it. Enhanced centerline (dashes flanking it) warns a hold line is within ~150 ft.'),
    A('Taxiway edge markings'),
    P('Double solid yellow: edge, do not cross. Dashed: the pavement beyond is usable (an apron, for example).'),
    A('Taxi shoulder markings'),
    P('Shoulders prevent erosion but may not support an airplane — the marked shoulder is not pavement for you.'),
    A('Surface painted direction & location signs'),
    P('Painted arrows and identifiers on the pavement itself when installing a sign is impractical.'),
    A('Geographic position markings'),
    P('The pink "spots" used as low-visibility taxi checkpoints — you report and hold at them in SMGCS operations.'),
    A('Holding position markings'),
    B('Four yellow lines — two solid, two dashed. Solid side is where you stop; cross only the dashed side. Always stop with a clearance question.'),
    P('The single dashed line across a taxiway is a taxiway/taxiway hold — used where ATC needs to hold traffic short of an intersection.', 3),
    A('Other markings'),
    P('Nonmovement area boundary: solid + dashed yellow pair separating your ramp from ATC\'s ground. ILS critical area and vehicle roadway markings round out the set.'),
    H('Runway Markings'),
    A('Runway designators & centerline'),
    P('Numbers = magnetic heading to the nearest 10°; L/R/C separate parallels. Centerline: white uniformly spaced stripes.'),
    P('Threshold, aiming point (the big blocks ~1000 ft in), and touchdown-zone markings complete the picture — displaced thresholds mean taxi yes, land beyond.', 3),
    H('Airport Signs'),
    A('Mandatory instruction signs'),
    B('Red background, white text — runway holding positions, ILS critical areas, no-entry. Red means a clearance is required.'),
    A('Location signs'),
    P('Black background, yellow letters — "you are HERE" (taxiway or runway you are ON).'),
    A('Runway boundary sign'),
    P('The hold-marking picture on a sign, facing the runway — it shows the exit side: you are not clear of the runway until you are past it.'),
    A('Direction, destination & information signs'),
    P('Yellow background, black text — direction (arrows at intersections), destination (arrows to runways/ramps), information (frequencies, procedures).'),
    A('Runway distance remaining signs'),
    P('Black with white numbers — thousands of feet of runway left.'),
    H('Airport Lighting'),
    A('Taxiway lighting'),
    P('Blue edge lights, green centerline lights; clearance bars and stop bars in low visibility.'),
    A('Runway lighting'),
    P('White edge lights (amber caution zone on the last 2000 ft of an instrument runway), green threshold / red end, centerline systems on precision runways.'),
    A('Runway Entrance Lights (REL)'),
    P('Runway status lights: flashing RED in the pavement at the entrance = a runway is unsafe to enter — stop regardless of clearance and ask.'),

    S('Operations & Risk Management'),
    H('Hold Lines — AI.II.C.R3'),
    B('Cross the dashed side, stop on the solid side, and NEVER cross onto a runway without an explicit clearance.'),
    P('During taxi: know where you are, know where the runway is, and treat every intersection as a decision point.'),
    H('RM: Landing & Rollout — AI.II.C.R6/R7'),
    P('Brief the landing rollout and the expected exit BEFORE the approach; exit the runway entirely; never cross another runway on the way in without clearance.'),
    H('RM: Night Operations — AI.II.C.R4'),
    P('Exterior lights day and night; slow down and double-check everything — the signage environment shrinks to what your taxi light touches.'),
    H('RM: Low Visibility — AI.II.C.R5'),
    P('AIM 4-3-19: slow, deliberate, diagram-out taxi; geographic position markings and stop bars exist for exactly this.'),
    H('RM: Loss of SA & Disorientation — AI.II.C.R1'),
    B('Lost on the field? STOP. Tell ATC (or announce on CTAF) and ask for progressive taxi. A stopped airplane has never caused an incursion.'),
    H('Case Study: United 1448 — Providence'),
    P('Night + low visibility + lost SA on the field, with a 757 departing through the fog. Walk the NTSB animation with the learner and pull out the mitigations: stop, ask, progressive taxi, never assume.'),

    S('Conclusion'),
    P('Review: what an incursion is · readbacks (enter/cross/hold short) · plan-brief-review · sterile flight deck · markings, signs, lights · hold lines · night, low vis, lost SA · United 1448.'),
    P('One habit covers most of it: never cross a hold line without saying the clearance out loud.'),
  ]};

})();
