/* custom.js — hand-authored scripts that survive build.py rebuilds.
   Loaded after data.js.

   window.CFI_SCRIPTS[lessonId] = { nodes: [...] }
     Seeds the "My Script" tab for that lesson with a pre-written teaching script.
     Every line stays editable / removable / note-able in the app.
     Node shape: { t: text, l: level (-1 section, 0 header, 1+ indent), b: bold }
*/
(function () {
  const S  = t => ({ t, l: -1, b: true });          // orange section
  const H  = t => ({ t, l: 0,  b: true });          // blue header
  const A  = t => ({ t, l: 1,  b: true, k: true }); // acronym letter / topic (k = force topic style)
  const P  = (t, l) => ({ t, l: l || 2, b: false }); // talking point
  const B  = (t, l) => ({ t, l: l || 2, b: true });  // emphasised point

  window.CFI_SCRIPTS = window.CFI_SCRIPTS || {};

  /* ============================================================
     I.A — Effects of Behavior & Communication on the Learning Process
     Flow follows the FIA Task A video; spine is the acronyms;
     detail augmented from the Backseat teach script + extra detail.
     ============================================================ */
  window.CFI_SCRIPTS['i-a-behavior-com-on-learning'] = { nodes: [

    S('Introduction'),
    H('Attention'),
    P('[Your hook here] — "You have spent years assuming people understood you. Unless you know this material, they did not."'),
    P('Alternate: ask them to think of the best and worst instructor they ever had, and what actually made the difference.'),
    H('Overview'),
    P('Foundations of human behavior → motivation → human needs (PSBECS) → defense mechanisms (DR DR F CPR) → learner struggles → communication (SSR / COIL / LIQIR).'),
    H('What'),
    P('How human behavior — needs, personalities, motivation, emotions, age — and communication affect the learning process.'),
    H('Why'),
    P('Learning is a change in behavior as a result of experience. To cause that change I have to know why people act the way they do.'),
    B('Self-application: once you can name your own defense mechanisms and motivators, you use this every day — that is what makes the FOI worth learning instead of dreading.'),

    S('How:'),

    /* ---------------- foundations ---------------- */
    H('Foundations of Human Behavior — FI.I.A.K1a'),
    A('Two definitions of human behavior'),
    P('1. The factors that cause people to act in predictable ways — behavior is a product of experience.'),
    P('Ex: how two learners take praise after a good landing — one relaxes into it, the other gets complacent — depends on how praise landed for them long before they met me.', 3),
    P('2. The attempt to satisfy human needs — simple (food, water) through complex (respect, acceptance).'),
    A('Life course of humans'),
    P('As people mature they move from dependency toward self-direction, so the age of the learner shapes how I design the curriculum.'),
    B('Big picture: a working knowledge of behavior helps me understand the learner — that is the whole point of this task.'),

    H('Instructor & Learner Relationship — FI.I.A.K1b'),
    P('Everyone has an individual style of learning; working with that style benefits both of us.'),
    P('The match — or mismatch — between my teaching style and their learning style drives instructional satisfaction.'),
    B('My job is two-part: identify MY teaching style, identify THEIR learning style, and meet in the middle.'),
    P('I think out loud through every maneuver; a quiet, methodical learner needs the whiteboard and ten seconds of silence to process the exact same thing.', 3),
    P('RM — Recognizing & Accommodating Human Behavior (FI.I.A.R1): adjust for different personalities, motivators, and learning styles.'),

    /* ---------------- motivation ---------------- */
    H('Motivation — FI.I.A.K1c'),
    P('The driving force a person feels when trying to accomplish a goal; it lies at the heart of goals and is likely the dominant force governing progress.'),
    B('There is always an exchange — five a.m. drives and $200 an hour, traded for the right seat.'),
    A('Motivation can be positive or negative, tangible or intangible, subtle or obvious'),
    P('Positive — awards, recognition, tangible returns, group belonging, favorable self-image, a safe and pleasant environment.'),
    P('Positive is almost always the better choice.', 3),
    P('Negative — threats, fear, criticism. May work short term, but creates insecure training, inhibits learning, and damages the relationship.'),
    P('Avoid it with everyone except the most overconfident and impulsive learner.', 3),
    A('Maintaining motivation'),
    P('Praise incremental successes and tie each accomplishment back to the lesson objective; keep presenting new challenges.'),
    P('Drops are natural once the initial excitement wears off — remind them of their goals and normalize plateaus.'),
    B('Takeaway: identify how this learner is motivated, then use it to keep them moving.'),

    /* ---------------- maslow ---------------- */
    H('Human Needs — Maslow\'s Hierarchy: PSBECS — FI.I.A.K1d'),
    P('Levels of importance. Until the lower needs are met, the higher ones cannot be — and the learner is not ready to learn.'),
    A('P — Physiological'),
    P('Biological needs: food, rest, water, protection from the elements.'),
    P('A learner who came straight off a ten-hour shift without eating spends the lesson thinking about food, not about pitch and power.', 3),
    P('Get ahead of it — food, water, and a bathroom stop before we walk out, instead of burning their money in the air.', 3),
    A('S — Safety & Security'),
    P('Protection against danger, threats, and deprivation — at home and in the airplane.'),
    P('An airplane they overheard getting squawked yesterday: they will spend the hour listening to the engine instead of flying it.', 3),
    A('B — Belonging'),
    P('The need to associate, and to give and receive friendship — loneliness and alienation are real at an unfamiliar flight school.'),
    P('Counter: the learner who only trains at odd hours and never meets anybody quietly decides they do not belong here — introduce them around and get them a study partner.', 3),
    A('E — Esteem'),
    P('Internal (self-esteem): confidence, independence, achievement, competence.'),
    P('External (reputation): status, recognition, appreciation, respect of associates.'),
    P('High esteem → confident, independent, motivated. Low esteem → insecure, quicker to quit on a problem.', 3),
    P('The learner who apologizes after every single landing is telling me their esteem needs work before their technique does.', 3),
    B('If esteem is not met they are not ready to learn — build them up and push them out of the comfort zone.', 3),
    A('C — Cognitive & Aesthetic (added years after the original theory)'),
    P('Cognitive: the need to know and understand — understanding lets them control the situation and make informed decisions.'),
    P('Say "lean the mixture" and it is gone by next lesson; show them a fouled plug and what detonation does to a piston and they never skip it again.', 3),
    P('Aesthetic: emotional needs — can they see the beauty in what they are learning? Do they enjoy the school, the airplane, the flying?'),
    B('The part I control: three hours in a hot cockpit beside someone who sighs at every mistake is unbearable — nobody learns in that seat. If an instructor dislikes a learner, it affects the ability to teach.', 3),
    A('S — Self-Actualization'),
    P('Realizing one\'s own potential; reachable only when every other need is satisfied.'),
    B('I cannot make anyone self-actualize — but I control everything underneath it, so I clear the path and create the opportunity.', 3),
    P('Law of Readiness ties it together: the learner must be physically and mentally ready. Verify readiness every lesson (IMSAFE + motivation techniques).'),

    /* ---------------- defense mechanisms ---------------- */
    H('Defense Mechanisms — DR DR F CPR — FI.I.A.K1e'),
    P('Subconscious, almost automatic, ego-protecting reactions to unpleasant situations — used to soften failure, relieve guilt, and protect self-worth.'),
    B('Why I care: spotting one tells me the learner is frustrated or uncomfortable, so I can defuse the cause instead of arguing with the reaction.'),
    A('D — Denial'),
    P('Refusal to accept reality because it is too threatening.'),
    P('I tell them they lost 300 feet in the steep turn and they answer, "no, I was within a hundred the whole way around."', 3),
    A('R — Repression'),
    P('Uncomfortable thoughts pushed into inaccessible areas of the unconscious mind.'),
    P('At debrief they cannot recall one thing about the go-around we just flew — the part that scared them is simply gone.', 3),
    A('D — Displacement'),
    P('Unconscious shift of emotion from the original object to a less threatening substitute.'),
    P('Frustrated in the pattern, and on the walk back in it is the airplane, the dispatcher, and the schedule that are the problem.', 3),
    B('I have full authority to say: "you seem frustrated — I am not comfortable flying right now." Use it.', 3),
    A('R — Rationalization'),
    P('Subconscious justification of actions that would otherwise be unacceptable; they sincerely believe the excuse.'),
    P('"These radios are junk" — after missing two calls because they were behind the airplane.', 3),
    A('F — Fantasy'),
    P('Daydreaming about how things should be rather than doing something about how they are.'),
    P('Dangerous: they can become satisfied with the daydream and stop chasing the goal — the whole debrief is about which airline they will fly for, not the three landings we need to fix.', 3),
    A('C — Compensation'),
    P('Disguising a weak quality by emphasizing a more positive one; may substitute an easier goal for the preferred one.'),
    P('"My landings are rough, but nobody in the class works the radio like I do."', 3),
    A('P — Projection'),
    P('Blame relegated to others for their own shortcomings and mistakes.'),
    P('"You never showed me that" — about the checklist flow we ran together the last two lessons.', 3),
    A('R — Reaction Formation'),
    P('Protecting against a dangerous desire by developing the opposite attitude — accepting or reacting opposite of the truth to avoid discomfort.'),
    P('White knuckles and a shaky voice after the unusual attitude recovery, and when I ask, they laugh and say that was fun. Consider ending the lesson right there — nothing more is going in.', 3),
    P('Non-aviation: insisting you were never that interested in the job you just got rejected from.', 3),
    A('Dealing with defense mechanisms'),
    B('Never confront the mechanism directly — that makes them more defensive. Create an environment where they do not need to defend themselves and address the root cause.'),

    /* ---------------- learner struggles ---------------- */
    S('Learner Struggles — Emotional Reactions (FI.I.A.K2)'),
    P('Analyze the learner\'s behavior before, during, and after every lesson so problems get identified and solved.'),
    H('Anxiety — FI.I.A.K2a'),
    P('"A state of mental uneasiness arising from fear" — the most significant psychological factor affecting flight instruction.'),
    P('Why: flying is threatening to the unfamiliar, and fear of falling is nearly universal.'),
    P('Reactions: hesitancy to act, the impulse to do something even if wrong, or freezing.'),
    P('Watch for it at: first flight, first solo, solo cross-countries, checkrides.'),
    P('Counter: normalize the feeling, reinforce enjoyment of flying, teach them to cope, and rebuild confidence — I would not sign them off unready.'),
    B('Never say "do not mess up my pass rate."'),
    H('Stress — FI.I.A.K2a'),
    P('The body\'s response to high demand.'),
    B('Low stress improves performance; high stress significantly degrades it. Finding that line per learner is the craft.'),
    P('Normal reactions: fast, accurate responses within the limits of their experience and training.'),
    P('First few landing lessons — I work the radio so their whole brain can go to the picture out the window.', 3),
    P('Two weeks from the checkride at a busy Class D — they work the radio, spot the traffic, and land it while I stay quiet.', 3),
    A('Abnormal reactions to stress (this one is about MY safety)'),
    P('Random, illogical, absent, or inadequate responses; over-cooperation, extreme self-control, inappropriate laughter or singing, rapid emotional shifts.'),
    P('If it concerns me: get on the ground and defuse the situation.'),
    P('After: refrain from instructing them, arrange an evaluation flight with a second instructor, and report to the FAA if serious psychological issues are at play.'),
    B('DO NOT ENDORSE THEM — I am liable.'),
    H('Impatience — FI.I.A.K2b'),
    P('Seeks the ultimate objective without considering the means — the learner who wants to solo by hour twelve and treats slow flight as a speed bump.'),
    P('Counter: present training one step at a time with clearly stated goals, tailored to their pace. Visible progress is what keeps them.'),
    H('Worry or Lack of Interest — FI.I.A.K2c'),
    P('Those worried or emotionally upset are not ready to learn and get little from instruction.'),
    P('Counter: divert attention from the worry to the task at hand.'),
    P('Prevent: make sure they know exactly how they progressed and what is deficient — say nothing about their landings and a worrier decides they were terrible.'),
    P('For lack of interest: remind them of the goals they told me on day one.'),
    H('Physical Discomfort, Illness, Fatigue & Dehydration — FI.I.A.K2d'),
    P('All slow the rate of learning and should be mitigated — run PAVE / IMSAFE. Ties straight back to physiological, the base of PSBECS.'),
    P('Fatigue is one of the most treacherous hazards to flight safety; it impairs judgment and decision making.'),
    P('Acute: normal part of everyday living. Chronic: physiological/psychological problems — do not fly.', 3),
    P('Dehydration reduces alertness; heatstroke is the body failing to control temperature. Carry water, keep it cool, wear light clothing.'),
    H('Apathy Due to Inadequate Instruction — FI.I.A.K2e'),
    P('Provide well-planned, accurate, meaningful instruction taught to the level of the learner.'),
    B('Let the ego go. Be vulnerable and own what I do not know — "great question, I am not sure; let me find out and get back to you."'),
    P('Pretend to know everything, get fact-checked once, and they will not believe anything I say afterward.'),
    P('Once the instructor loses their confidence it is very hard to regain, and learning is diminished.'),
    P('Bonus: "I stumped the CFI" sparks a competitive fire that pushes us both.', 3),
    H('Teaching the Adult Learner — FI.I.A.K3'),
    P('Most student pilots are adults: autonomous and self-directed, goal and relevancy oriented, practical, drawing on a foundation of life experience, and needing to be shown respect.'),
    P('They may be slower to grasp a brand-new concept than a younger learner — the same reason a new language comes easier at ten than at forty.'),
    P('So I: clarify expectations early, use an organized syllabus with clear objectives, let them control pace, use scenario-based training, connect new ideas to what they know, and refrain from spoon-feeding.'),

    /* ---------------- communication ---------------- */
    S('Effective Communication — FI.I.A.K4'),
    P('It does not happen automatically — I have to develop a style that actually conveys information.'),
    P('Communication takes place when a person transmits ideas or feelings to another; its effectiveness is measured by how closely the idea received matches the idea sent.'),
    B('Goal: a change in behavior.'),
    H('Basic Elements — SSR — FI.I.A.K4a'),
    A('S — Source (the sender, speaker, transmitter — me)'),
    P('Effectiveness rests on three factors: ability to select and use language, revealing a positive attitude about self and material, and material that is accurate, current, and stimulating.'),
    A('S — Symbol (the words, signs, or oral/visual/tactile codes carrying the message)'),
    P('Choose the symbols best for opening, explaining, clarifying, emphasizing, and closing — and the medium best suited to carry them.'),
    P('Monitor feedback; if it is not landing, change the symbol — a traffic pattern described out loud is a blur, drawn on the whiteboard it is obvious.', 3),
    P('Learners need feedback on how they are doing; deliver negative feedback in private only.'),
    A('R — Receiver (the listener, reader, learner)'),
    P('Communication is effective when the receiver reacts with understanding and changes behavior accordingly.'),
    P('Not everyone learns the same way — using multiple approaches is most effective.'),
    H('Barriers to Effective Communication — COIL — FI.I.A.K4b / R2'),
    A('C — Confusion between the symbol and the symbolized object'),
    P('The meaning or intent of the words, or the context, is not clear — sarcasm, or a word with two meanings.'),
    P('"Level off" — do they stop the climb, or roll the wings level?', 3),
    A('O — Overuse of Abstractions'),
    P('Abstractions are general rather than specific words; they may not evoke the same experience in the learner\'s mind.'),
    P('"Slow it down" on final — pitch, power, or flaps? Say "1500 RPM and 65 knots" instead.', 3),
    A('I — Interference'),
    P('The message gets disrupted or truncated — confirm it was understood.'),
    P('External factors outside my control: physiological (injury, hearing loss), environmental (noise, radio static, busy frequency), psychological (fear, mistrust).'),
    P('Prior learning interferes too — years of driving says steer with your hands, so the yoke fights them all the way down the taxiway.', 3),
    A('L — Lack of Common Experience'),
    B('The greatest single barrier to effective communication.'),
    P('I must speak the same language as the learner; when specific terminology is required, confirm they understand it.'),
    P('"Make short approach," "squawk VFR," "expedite" — obvious to me, noise to a ten-hour student unless I brief the words on the ground.', 3),
    P('Generational gap between a young CFI and an adult learner counts here too.', 3),
    H('Developing Communication Skills — LIQIR — FI.I.A.K4c'),
    A('L — Listening'),
    P('Listen actively and listen to understand rather than to refute — notes, eye contact, and hear the question they are actually asking.'),
    A('I — Instructional Communication'),
    P('Know the topic cold and be confident; use stories and past experience to illustrate points and hold attention; evaluate to confirm the level of understanding.'),
    A('Q — Questioning'),
    P('Good questioning determines how well the learner understands. Ask open-ended, focused questions; paraphrase and perception-check to confirm.'),
    A('I — Instructional Enhancement'),
    P('The deeper my knowledge of an area, the better I convey it — and the more confident and efficient I am.'),
    B('If I cannot explain it simply, I do not understand it well enough yet.', 3),
    A('R — Role Playing'),
    P('Practice instructing to build the skill; play ATC for the learner so the radios stop being a threat and their confidence builds before the real thing.'),

    S('Conclusion'),
    P('Brief review: foundations → motivation → PSBECS → DR DR F CPR → learner struggles → SSR / COIL / LIQIR.'),
    P('Tie back to why: every one of these is a tool for spotting what is blocking the learner and removing it.'),
  ]};

})();
